language: node_js
sudo: false

node_js:
  - "11"

notifications:
  email: false

cache:
  directories:
  - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - g++-8
      - cmake
