/** Declaration file generated by dts-gen */

export const BEIGE: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const BLACK: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const BLANK: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const BLEND_ADDITIVE: number;

export const BLEND_ALPHA: number;

export const BLEND_MULTIPLIED: number;

export const BLUE: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const BROWN: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const CAMERA_CUSTOM: number;

export const CAMERA_FIRST_PERSON: number;

export const CAMERA_FREE: number;

export const CAMERA_ORBITAL: number;

export const CAMERA_ORTHOGRAPHIC: number;

export const CAMERA_PERSPECTIVE: number;

export const CAMERA_THIRD_PERSON: number;

export const COMPRESSED_ASTC_4x4_RGBA: number;

export const COMPRESSED_ASTC_8x8_RGBA: number;

export const COMPRESSED_DXT1_RGB: number;

export const COMPRESSED_DXT1_RGBA: number;

export const COMPRESSED_DXT3_RGBA: number;

export const COMPRESSED_DXT5_RGBA: number;

export const COMPRESSED_ETC1_RGB: number;

export const COMPRESSED_ETC2_EAC_RGBA: number;

export const COMPRESSED_ETC2_RGB: number;

export const COMPRESSED_PVRT_RGB: number;

export const COMPRESSED_PVRT_RGBA: number;

export const CUBEMAP_AUTO_DETECT: number;

export const CUBEMAP_CROSS_FOUR_BY_THREE: number;

export const CUBEMAP_CROSS_THREE_BY_FOUR: number;

export const CUBEMAP_LINE_HORIZONTAL: number;

export const CUBEMAP_LINE_VERTICAL: number;

export const CUBEMAP_PANORAMA: number;

export const DARKBLUE: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const DARKBROWN: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const DARKGRAY: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const DARKGREEN: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const DARKPURPLE: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const DEFAULT_BATCH_BUFFERS: number;

export const DEFAULT_BATCH_BUFFER_ELEMENTS: number;

export const DEFAULT_BATCH_DRAWCALLS: number;

export const DEG2RAD: number;

export const FILTER_ANISOTROPIC_16X: number;

export const FILTER_ANISOTROPIC_4X: number;

export const FILTER_ANISOTROPIC_8X: number;

export const FILTER_BILINEAR: number;

export const FILTER_POINT: number;

export const FILTER_TRILINEAR: number;

export const FLAG_FULLSCREEN_MODE: number;

export const FLAG_MSAA_4X_HINT: number;

export const FLAG_RESERVED: number;

export const FLAG_VSYNC_HINT: number;

export const FLAG_WINDOW_ALWAYS_RUN: number;

export const FLAG_WINDOW_HIDDEN: number;

export const FLAG_WINDOW_RESIZABLE: number;

export const FLAG_WINDOW_TRANSPARENT: number;

export const FLAG_WINDOW_UNDECORATED: number;

export const FONT_BITMAP: number;

export const FONT_DEFAULT: number;

export const FONT_SDF: number;

export const GAMEPAD_AXIS_LEFT_TRIGGER: number;

export const GAMEPAD_AXIS_LEFT_X: number;

export const GAMEPAD_AXIS_LEFT_Y: number;

export const GAMEPAD_AXIS_RIGHT_TRIGGER: number;

export const GAMEPAD_AXIS_RIGHT_X: number;

export const GAMEPAD_AXIS_RIGHT_Y: number;

export const GAMEPAD_AXIS_UNKNOWN: number;

export const GAMEPAD_BUTTON_LEFT_FACE_DOWN: number;

export const GAMEPAD_BUTTON_LEFT_FACE_LEFT: number;

export const GAMEPAD_BUTTON_LEFT_FACE_RIGHT: number;

export const GAMEPAD_BUTTON_LEFT_FACE_UP: number;

export const GAMEPAD_BUTTON_LEFT_THUMB: number;

export const GAMEPAD_BUTTON_LEFT_TRIGGER_1: number;

export const GAMEPAD_BUTTON_LEFT_TRIGGER_2: number;

export const GAMEPAD_BUTTON_MIDDLE: number;

export const GAMEPAD_BUTTON_MIDDLE_LEFT: number;

export const GAMEPAD_BUTTON_MIDDLE_RIGHT: number;

export const GAMEPAD_BUTTON_RIGHT_FACE_DOWN: number;

export const GAMEPAD_BUTTON_RIGHT_FACE_LEFT: number;

export const GAMEPAD_BUTTON_RIGHT_FACE_RIGHT: number;

export const GAMEPAD_BUTTON_RIGHT_FACE_UP: number;

export const GAMEPAD_BUTTON_RIGHT_THUMB: number;

export const GAMEPAD_BUTTON_RIGHT_TRIGGER_1: number;

export const GAMEPAD_BUTTON_RIGHT_TRIGGER_2: number;

export const GAMEPAD_BUTTON_UNKNOWN: number;

export const GAMEPAD_PLAYER1: number;

export const GAMEPAD_PLAYER2: number;

export const GAMEPAD_PLAYER3: number;

export const GAMEPAD_PLAYER4: number;

export const GESTURE_DOUBLETAP: number;

export const GESTURE_DRAG: number;

export const GESTURE_HOLD: number;

export const GESTURE_NONE: number;

export const GESTURE_PINCH_IN: number;

export const GESTURE_PINCH_OUT: number;

export const GESTURE_SWIPE_DOWN: number;

export const GESTURE_SWIPE_LEFT: number;

export const GESTURE_SWIPE_RIGHT: number;

export const GESTURE_SWIPE_UP: number;

export const GESTURE_TAP: number;

export const GOLD: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const GRAPHICS_API_OPENGL_11: boolean;

export const GRAPHICS_API_OPENGL_21: boolean;

export const GRAPHICS_API_OPENGL_33: boolean;

export const GRAPHICS_API_OPENGL_ES2: boolean;

export const GRAY: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const GREEN: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const KEY_A: number;

export const KEY_APOSTROPHE: number;

export const KEY_B: number;

export const KEY_BACK: number;

export const KEY_BACKSLASH: number;

export const KEY_BACKSPACE: number;

export const KEY_C: number;

export const KEY_CAPS_LOCK: number;

export const KEY_COMMA: number;

export const KEY_D: number;

export const KEY_DELETE: number;

export const KEY_DOWN: number;

export const KEY_E: number;

export const KEY_EIGHT: number;

export const KEY_END: number;

export const KEY_ENTER: number;

export const KEY_EQUAL: number;

export const KEY_ESCAPE: number;

export const KEY_F: number;

export const KEY_F1: number;

export const KEY_F10: number;

export const KEY_F11: number;

export const KEY_F12: number;

export const KEY_F2: number;

export const KEY_F3: number;

export const KEY_F4: number;

export const KEY_F5: number;

export const KEY_F6: number;

export const KEY_F7: number;

export const KEY_F8: number;

export const KEY_F9: number;

export const KEY_FIVE: number;

export const KEY_FOUR: number;

export const KEY_G: number;

export const KEY_GRAVE: number;

export const KEY_H: number;

export const KEY_HOME: number;

export const KEY_I: number;

export const KEY_INSERT: number;

export const KEY_J: number;

export const KEY_K: number;

export const KEY_KB_MENU: number;

export const KEY_KP_0: number;

export const KEY_KP_1: number;

export const KEY_KP_2: number;

export const KEY_KP_3: number;

export const KEY_KP_4: number;

export const KEY_KP_5: number;

export const KEY_KP_6: number;

export const KEY_KP_7: number;

export const KEY_KP_8: number;

export const KEY_KP_9: number;

export const KEY_KP_ADD: number;

export const KEY_KP_DECIMAL: number;

export const KEY_KP_DIVIDE: number;

export const KEY_KP_ENTER: number;

export const KEY_KP_EQUAL: number;

export const KEY_KP_MULTIPLY: number;

export const KEY_KP_SUBTRACT: number;

export const KEY_L: number;

export const KEY_LEFT: number;

export const KEY_LEFT_ALT: number;

export const KEY_LEFT_BRACKET: number;

export const KEY_LEFT_CONTROL: number;

export const KEY_LEFT_SHIFT: number;

export const KEY_LEFT_SUPER: number;

export const KEY_M: number;

export const KEY_MENU: number;

export const KEY_MINUS: number;

export const KEY_N: number;

export const KEY_NINE: number;

export const KEY_NUM_LOCK: number;

export const KEY_O: number;

export const KEY_ONE: number;

export const KEY_P: number;

export const KEY_PAGE_DOWN: number;

export const KEY_PAGE_UP: number;

export const KEY_PAUSE: number;

export const KEY_PERIOD: number;

export const KEY_PRINT_SCREEN: number;

export const KEY_Q: number;

export const KEY_R: number;

export const KEY_RIGHT: number;

export const KEY_RIGHT_ALT: number;

export const KEY_RIGHT_BRACKET: number;

export const KEY_RIGHT_CONTROL: number;

export const KEY_RIGHT_SHIFT: number;

export const KEY_RIGHT_SUPER: number;

export const KEY_S: number;

export const KEY_SCROLL_LOCK: number;

export const KEY_SEMICOLON: number;

export const KEY_SEVEN: number;

export const KEY_SIX: number;

export const KEY_SLASH: number;

export const KEY_SPACE: number;

export const KEY_T: number;

export const KEY_TAB: number;

export const KEY_THREE: number;

export const KEY_TWO: number;

export const KEY_U: number;

export const KEY_UP: number;

export const KEY_V: number;

export const KEY_VOLUME_DOWN: number;

export const KEY_VOLUME_UP: number;

export const KEY_W: number;

export const KEY_X: number;

export const KEY_Y: number;

export const KEY_Z: number;

export const KEY_ZERO: number;

export const LIGHTGRAY: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const LIME: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const LOC_COLOR_AMBIENT: number;

export const LOC_COLOR_DIFFUSE: number;

export const LOC_COLOR_SPECULAR: number;

export const LOC_MAP_ALBEDO: number;

export const LOC_MAP_BRDF: number;

export const LOC_MAP_CUBEMAP: number;

export const LOC_MAP_DIFFUSE: number;

export const LOC_MAP_EMISSION: number;

export const LOC_MAP_HEIGHT: number;

export const LOC_MAP_IRRADIANCE: number;

export const LOC_MAP_METALNESS: number;

export const LOC_MAP_NORMAL: number;

export const LOC_MAP_OCCLUSION: number;

export const LOC_MAP_PREFILTER: number;

export const LOC_MAP_ROUGHNESS: number;

export const LOC_MAP_SPECULAR: number;

export const LOC_MATRIX_MODEL: number;

export const LOC_MATRIX_MVP: number;

export const LOC_MATRIX_PROJECTION: number;

export const LOC_MATRIX_VIEW: number;

export const LOC_VECTOR_VIEW: number;

export const LOC_VERTEX_COLOR: number;

export const LOC_VERTEX_NORMAL: number;

export const LOC_VERTEX_POSITION: number;

export const LOC_VERTEX_TANGENT: number;

export const LOC_VERTEX_TEXCOORD01: number;

export const LOC_VERTEX_TEXCOORD02: number;

export const LOG_ALL: number;

export const LOG_DEBUG: number;

export const LOG_ERROR: number;

export const LOG_FATAL: number;

export const LOG_INFO: number;

export const LOG_NONE: number;

export const LOG_TRACE: number;

export const LOG_WARNING: number;

export const MAGENTA: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const MAP_ALBEDO: number;

export const MAP_BRDF: number;

export const MAP_CUBEMAP: number;

export const MAP_DIFFUSE: number;

export const MAP_EMISSION: number;

export const MAP_HEIGHT: number;

export const MAP_IRRADIANCE: number;

export const MAP_METALNESS: number;

export const MAP_NORMAL: number;

export const MAP_OCCLUSION: number;

export const MAP_PREFILTER: number;

export const MAP_ROUGHNESS: number;

export const MAP_SPECULAR: number;

export const MAROON: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const MAX_GAMEPADS: number;

export const MAX_GAMEPAD_AXIS: number;

export const MAX_GAMEPAD_BUTTONS: number;

export const MAX_KEY_PRESSED_QUEUE: number;

export const MAX_MATERIAL_MAPS: number;

export const MAX_MATRIX_STACK_SIZE: number;

export const MAX_SHADER_LOCATIONS: number;

export const MAX_TOUCH_POINTS: number;

export const MOUSE_LEFT_BUTTON: number;

export const MOUSE_MIDDLE_BUTTON: number;

export const MOUSE_RIGHT_BUTTON: number;

export const NPT_3PATCH_HORIZONTAL: number;

export const NPT_3PATCH_VERTICAL: number;

export const NPT_9PATCH: number;

export const ORANGE: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const PI: number;

export const PINK: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const PURPLE: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const RAD2DEG: number;

export const RAYWHITE: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const RED: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const RL_CULL_DISTANCE_FAR: number;

export const RL_CULL_DISTANCE_NEAR: number;

export const RL_FILTER_LINEAR: number;

export const RL_FILTER_LINEAR_MIP_NEAREST: number;

export const RL_FILTER_MIP_LINEAR: number;

export const RL_FILTER_MIP_NEAREST: number;

export const RL_FILTER_NEAREST: number;

export const RL_FILTER_NEAREST_MIP_LINEAR: number;

export const RL_LINES: number;

export const RL_MODELVIEW: number;

export const RL_PROJECTION: number;

export const RL_QUADS: number;

export const RL_TEXTURE: number;

export const RL_TEXTURE_ANISOTROPIC_FILTER: number;

export const RL_TEXTURE_MAG_FILTER: number;

export const RL_TEXTURE_MIN_FILTER: number;

export const RL_TEXTURE_WRAP_S: number;

export const RL_TEXTURE_WRAP_T: number;

export const RL_TRIANGLES: number;

export const RL_WRAP_CLAMP: number;

export const RL_WRAP_MIRROR_CLAMP: number;

export const RL_WRAP_MIRROR_REPEAT: number;

export const RL_WRAP_REPEAT: number;

export const SKYBLUE: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const UNCOMPRESSED_GRAYSCALE: number;

export const UNCOMPRESSED_GRAY_ALPHA: number;

export const UNCOMPRESSED_R32: number;

export const UNCOMPRESSED_R32G32B32: number;

export const UNCOMPRESSED_R32G32B32A32: number;

export const UNCOMPRESSED_R4G4B4A4: number;

export const UNCOMPRESSED_R5G5B5A1: number;

export const UNCOMPRESSED_R5G6B5: number;

export const UNCOMPRESSED_R8G8B8: number;

export const UNCOMPRESSED_R8G8B8A8: number;

export const UNIFORM_FLOAT: number;

export const UNIFORM_INT: number;

export const UNIFORM_IVEC2: number;

export const UNIFORM_IVEC3: number;

export const UNIFORM_IVEC4: number;

export const UNIFORM_SAMPLER2D: number;

export const UNIFORM_VEC2: number;

export const UNIFORM_VEC3: number;

export const UNIFORM_VEC4: number;

export const VIOLET: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const WHITE: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const WRAP_CLAMP: number;

export const WRAP_MIRROR_CLAMP: number;

export const WRAP_MIRROR_REPEAT: number;

export const WRAP_REPEAT: number;

export const YELLOW: {
    a: number;
    b: number;
    g: number;
    r: number;
};

export const path: string;

export function BeginBlendMode(): any;

export function BeginDrawing(): any;

export function BeginMode2D(): any;

export function BeginMode3D(): any;

export function BeginScissorMode(): any;

export function BeginShaderMode(): any;

export function BeginTextureMode(): any;

export function BeginVrDrawing(): any;

export function Camera(position: any, target: any, up: any, fovy: any, type: any): any;

export function Camera2D(offset: any, target: any, rotation: any, zoom: any): any;

export function Camera3D(position: any, target: any, up: any, fovy: any, type: any): any;

export function ChangeDirectory(): any;

export function CheckCollisionBoxSphere(): any;

export function CheckCollisionBoxes(): any;

export function CheckCollisionCircleRec(): any;

export function CheckCollisionCircles(): any;

export function CheckCollisionPointCircle(): any;

export function CheckCollisionPointRec(): any;

export function CheckCollisionPointTriangle(): any;

export function CheckCollisionRayBox(): any;

export function CheckCollisionRaySphere(): any;

export function CheckCollisionRaySphereEx(): any;

export function CheckCollisionRecs(): any;

export function CheckCollisionSpheres(): any;

export function Clamp(): any;

export function ClearBackground(): any;

export function ClearDirectoryFiles(): any;

export function ClearDroppedFiles(): any;

export function CloseAudioDevice(): any;

export function CloseAudioStream(): any;

export function CloseVrSimulator(): any;

export function CloseWindow(): any;

export function CodepointToUtf8(): any;

export function Color(red: any, green: any, blue: any, alpha: any): any;

export function ColorFromHSV(): any;

export function ColorFromNormalized(): any;

export function ColorNormalize(): any;

export function ColorToHSV(): any;

export function ColorToInt(): any;

export function CompressData(): any;

export function DecompressData(): any;

export function DirectoryExists(): any;

export function DisableCursor(): any;

export function DrawBillboard(): any;

export function DrawBillboardRec(): any;

export function DrawBoundingBox(): any;

export function DrawCircle(): any;

export function DrawCircle3D(): any;

export function DrawCircleGradient(): any;

export function DrawCircleLines(): any;

export function DrawCircleSector(): any;

export function DrawCircleSectorLines(): any;

export function DrawCircleV(): any;

export function DrawCube(): any;

export function DrawCubeTexture(): any;

export function DrawCubeV(): any;

export function DrawCubeWires(): any;

export function DrawCubeWiresV(): any;

export function DrawCylinder(): any;

export function DrawCylinderWires(): any;

export function DrawEllipse(): any;

export function DrawEllipseLines(): any;

export function DrawFPS(): any;

export function DrawGizmo(): any;

export function DrawGrid(): any;

export function DrawLine(): any;

export function DrawLine3D(): any;

export function DrawLineBezier(): any;

export function DrawLineEx(): any;

export function DrawLineStrip(): any;

export function DrawLineV(): any;

export function DrawPixel(): any;

export function DrawPixelV(): any;

export function DrawPlane(): any;

export function DrawPoint3D(): any;

export function DrawPoly(): any;

export function DrawPolyLines(): any;

export function DrawRay(): any;

export function DrawRectangle(): any;

export function DrawRectangleGradientEx(): any;

export function DrawRectangleGradientH(): any;

export function DrawRectangleGradientV(): any;

export function DrawRectangleLines(): any;

export function DrawRectangleLinesEx(): any;

export function DrawRectanglePro(): any;

export function DrawRectangleRec(): any;

export function DrawRectangleRounded(): any;

export function DrawRectangleRoundedLines(): any;

export function DrawRectangleV(): any;

export function DrawRing(): any;

export function DrawRingLines(): any;

export function DrawSphere(): any;

export function DrawSphereEx(): any;

export function DrawSphereWires(): any;

export function DrawText(): any;

export function DrawTextCodepoint(): any;

export function DrawTextEx(): any;

export function DrawTextRec(): any;

export function DrawTexture(): any;

export function DrawTextureEx(): any;

export function DrawTextureNPatch(): any;

export function DrawTexturePro(): any;

export function DrawTextureQuad(): any;

export function DrawTextureRec(): any;

export function DrawTextureV(): any;

export function DrawTriangle(): any;

export function DrawTriangle3D(): any;

export function DrawTriangleFan(): any;

export function DrawTriangleLines(): any;

export function DrawTriangleStrip(): any;

export function DrawTriangleStrip3D(): any;

export function EnableCursor(): any;

export function EndBlendMode(): any;

export function EndDrawing(): any;

export function EndMode2D(): any;

export function EndMode3D(): any;

export function EndScissorMode(): any;

export function EndShaderMode(): any;

export function EndTextureMode(): any;

export function EndVrDrawing(): any;

export function ExportImage(): any;

export function ExportImageAsCode(): any;

export function ExportWave(): any;

export function ExportWaveAsCode(): any;

export function Fade(): any;

export function FileExists(): any;

export function FormatText(args: any): any;

export function GenImageCellular(): any;

export function GenImageChecked(): any;

export function GenImageColor(): any;

export function GenImageFontAtlas(): any;

export function GenImageGradientH(): any;

export function GenImageGradientRadial(): any;

export function GenImageGradientV(): any;

export function GenImagePerlinNoise(): any;

export function GenImageWhiteNoise(): any;

export function GenTextureBRDF(): any;

export function GenTextureCubemap(): any;

export function GenTextureIrradiance(): any;

export function GenTextureMipmaps(): any;

export function GenTexturePrefilter(): any;

export function GetCameraMatrix(): any;

export function GetCameraMatrix2D(): any;

export function GetClipboardText(): any;

export function GetCodepoints(): any;

export function GetCodepointsCount(): any;

export function GetCollisionRayGround(): any;

export function GetCollisionRayModel(): any;

export function GetCollisionRayTriangle(): any;

export function GetCollisionRec(): any;

export function GetColor(): any;

export function GetDirectoryFiles(): any;

export function GetDirectoryPath(): any;

export function GetDroppedFiles(): any;

export function GetExtension(): any;

export function GetFPS(): any;

export function GetFileModTime(): any;

export function GetFileName(): any;

export function GetFileNameWithoutExt(): any;

export function GetFontDefault(): any;

export function GetFrameTime(): any;

export function GetGamepadAxisCount(): any;

export function GetGamepadAxisMovement(): any;

export function GetGamepadButtonPressed(): any;

export function GetGamepadName(): any;

export function GetGestureDetected(): any;

export function GetGestureDragAngle(): any;

export function GetGestureDragVector(): any;

export function GetGestureHoldDuration(): any;

export function GetGesturePinchAngle(): any;

export function GetGesturePinchVector(): any;

export function GetGlyphIndex(): any;

export function GetImageAlphaBorder(): any;

export function GetImageData(): any;

export function GetImageDataNormalized(): any;

export function GetKeyPressed(): any;

export function GetMatrixProjection(): any;

export function GetMonitorCount(): any;

export function GetMonitorHeight(): any;

export function GetMonitorName(): any;

export function GetMonitorPhysicalHeight(): any;

export function GetMonitorPhysicalWidth(): any;

export function GetMonitorWidth(): any;

export function GetMousePosition(): any;

export function GetMouseRay(): any;

export function GetMouseWheelMove(): any;

export function GetMouseX(): any;

export function GetMouseY(): any;

export function GetMusicTimeLength(): any;

export function GetMusicTimePlayed(): any;

export function GetNextCodepoint(): any;

export function GetPixelDataSize(): any;

export function GetPrevDirectoryPath(): any;

export function GetRandomValue(): any;

export function GetScreenData(): any;

export function GetScreenHeight(): any;

export function GetScreenToWorld2D(): any;

export function GetScreenWidth(): any;

export function GetShaderDefault(): any;

export function GetShaderLocation(): any;

export function GetShapesTexture(): any;

export function GetShapesTextureRec(): any;

export function GetSoundsPlaying(): any;

export function GetTextureData(): any;

export function GetTextureDefault(): any;

export function GetTime(): any;

export function GetTouchPointsCount(): any;

export function GetTouchPosition(): any;

export function GetTouchX(): any;

export function GetTouchY(): any;

export function GetWaveData(): any;

export function GetWindowHandle(): any;

export function GetWindowPosition(): any;

export function GetWindowScaleDPI(): any;

export function GetWorkingDirectory(): any;

export function GetWorldToScreen(): any;

export function GetWorldToScreen2D(): any;

export function GetWorldToScreenEx(): any;

export function HideCursor(): any;

export function HideWindow(): any;

export function ImageAlphaClear(): any;

export function ImageAlphaCrop(): any;

export function ImageAlphaMask(): any;

export function ImageAlphaPremultiply(): any;

export function ImageClearBackground(): any;

export function ImageColorBrightness(): any;

export function ImageColorContrast(): any;

export function ImageColorGrayscale(): any;

export function ImageColorInvert(): any;

export function ImageColorReplace(): any;

export function ImageColorTint(): any;

export function ImageCopy(): any;

export function ImageCrop(): any;

export function ImageDither(): any;

export function ImageDraw(): any;

export function ImageDrawCircle(): any;

export function ImageDrawCircleV(): any;

export function ImageDrawLine(): any;

export function ImageDrawLineV(): any;

export function ImageDrawPixel(): any;

export function ImageDrawPixelV(): any;

export function ImageDrawRectangle(): any;

export function ImageDrawRectangleLines(): any;

export function ImageDrawRectangleRec(): any;

export function ImageDrawRectangleV(): any;

export function ImageDrawText(): any;

export function ImageDrawTextEx(): any;

export function ImageExtractPalette(): any;

export function ImageFlipHorizontal(): any;

export function ImageFlipVertical(): any;

export function ImageFormat(): any;

export function ImageFromImage(): any;

export function ImageMipmaps(): any;

export function ImageResize(): any;

export function ImageResizeCanvas(): any;

export function ImageResizeNN(): any;

export function ImageRotateCCW(): any;

export function ImageRotateCW(): any;

export function ImageText(): any;

export function ImageTextEx(): any;

export function ImageToPOT(): any;

export function InitAudioDevice(): any;

export function InitAudioStream(): any;

export function InitVrSimulator(): any;

export function InitWindow(): any;

export function IsAudioDeviceReady(): any;

export function IsAudioStreamPlaying(): any;

export function IsAudioStreamProcessed(): any;

export function IsCursorHidden(): any;

export function IsFileDropped(): any;

export function IsFileExtension(): any;

export function IsGamepadAvailable(): any;

export function IsGamepadButtonDown(): any;

export function IsGamepadButtonPressed(): any;

export function IsGamepadButtonReleased(): any;

export function IsGamepadButtonUp(): any;

export function IsGamepadName(): any;

export function IsGestureDetected(): any;

export function IsKeyDown(): any;

export function IsKeyPressed(): any;

export function IsKeyReleased(): any;

export function IsKeyUp(): any;

export function IsMouseButtonDown(): any;

export function IsMouseButtonPressed(): any;

export function IsMouseButtonReleased(): any;

export function IsMouseButtonUp(): any;

export function IsMusicPlaying(): any;

export function IsSoundPlaying(): any;

export function IsVrSimulatorReady(): any;

export function IsWindowFocused(): any;

export function IsWindowFullscreen(): any;

export function IsWindowHidden(): any;

export function IsWindowMinimized(): any;

export function IsWindowReady(): any;

export function IsWindowResized(): any;

export function Lerp(): any;

export function LoadFileData(): any;

export function LoadFileText(): any;

export function LoadFont(): any;

export function LoadFontData(): any;

export function LoadFontEx(): any;

export function LoadFontFromImage(): any;

export function LoadImage(): any;

export function LoadImageEx(): any;

export function LoadImageRaw(): any;

export function LoadMusicStream(): any;

export function LoadRenderTexture(): any;

export function LoadShader(): any;

export function LoadShaderCode(): any;

export function LoadSound(): any;

export function LoadSoundFromWave(): any;

export function LoadStorageValue(): any;

export function LoadText(): any;

export function LoadTexture(): any;

export function LoadTextureCubemap(): any;

export function LoadTextureFromImage(): any;

export function LoadWave(): any;

export function MatrixAdd(): any;

export function MatrixDeterminant(): any;

export function MatrixFrustum(): any;

export function MatrixIdentity(): any;

export function MatrixInvert(): any;

export function MatrixLookAt(): any;

export function MatrixMultiply(): any;

export function MatrixNormalize(): any;

export function MatrixOrtho(): any;

export function MatrixPerspective(): any;

export function MatrixRotate(): any;

export function MatrixRotateX(): any;

export function MatrixRotateXYZ(): any;

export function MatrixRotateY(): any;

export function MatrixRotateZ(): any;

export function MatrixScale(): any;

export function MatrixSubtract(): any;

export function MatrixTrace(): any;

export function MatrixTranslate(): any;

export function MatrixTranspose(): any;

export function MeasureText(): any;

export function MeasureTextEx(): any;

export function OpenURL(): any;

export function PauseAudioStream(): any;

export function PauseMusicStream(): any;

export function PauseSound(): any;

export function PlayAudioStream(): any;

export function PlayMusicStream(): any;

export function PlaySound(): any;

export function PlaySoundMulti(): any;

export function QuaternionAdd(): any;

export function QuaternionAddValue(): any;

export function QuaternionDivide(): any;

export function QuaternionFromAxisAngle(): any;

export function QuaternionFromEuler(): any;

export function QuaternionFromMatrix(): any;

export function QuaternionFromVector3ToVector3(): any;

export function QuaternionIdentity(): any;

export function QuaternionInvert(): any;

export function QuaternionLength(): any;

export function QuaternionLerp(): any;

export function QuaternionMultiply(): any;

export function QuaternionNormalize(): any;

export function QuaternionScale(): any;

export function QuaternionSlerp(): any;

export function QuaternionSubtract(): any;

export function QuaternionSubtractValue(): any;

export function QuaternionToAxisAngle(): any;

export function QuaternionToEuler(): any;

export function QuaternionToMatrix(): any;

export function QuaternionTransform(): any;

export function Ray(position: any, direction: any): any;

export function RayHitInfo(hit: any, distance: any, position: any, normal: any): any;

export function Rectangle(x: any, y: any, width: any, height: any): any;

export function ResumeAudioStream(): any;

export function ResumeMusicStream(): any;

export function ResumeSound(): any;

export function SaveFileData(): any;

export function SaveFileText(): any;

export function SaveStorageValue(): any;

export function SetAudioStreamBufferSizeDefault(): any;

export function SetAudioStreamPitch(): any;

export function SetAudioStreamVolume(): any;

export function SetCameraAltControl(): any;

export function SetCameraMode(): any;

export function SetCameraMoveControls(): any;

export function SetCameraPanControl(): any;

export function SetCameraSmoothZoomControl(): any;

export function SetClipboardText(): any;

export function SetConfigFlags(): any;

export function SetExitKey(): any;

export function SetGesturesEnabled(): any;

export function SetMasterVolume(): any;

export function SetMatrixProjection(): any;

export function SetMouseOffset(): any;

export function SetMousePosition(): any;

export function SetMouseScale(): any;

export function SetMusicLoopCount(): any;

export function SetMusicPitch(): any;

export function SetMusicVolume(): any;

export function SetShaderValue(): any;

export function SetShaderValueMatrix(): any;

export function SetShaderValueTexture(): any;

export function SetShaderValueV(): any;

export function SetShapesTexture(): any;

export function SetSoundPitch(): any;

export function SetSoundVolume(): any;

export function SetTargetFPS(): any;

export function SetTextureFilter(): any;

export function SetTextureWrap(): any;

export function SetTraceLogExit(): any;

export function SetTraceLogLevel(): any;

export function SetVrConfiguration(): any;

export function SetWindowIcon(): any;

export function SetWindowMinSize(): any;

export function SetWindowMonitor(): any;

export function SetWindowPosition(): any;

export function SetWindowSize(): any;

export function SetWindowTitle(): any;

export function Shader(id: any, locs: any): any;

export function ShowCursor(): any;

export function ShowWindow(): any;

export function StopAudioStream(): any;

export function StopMusicStream(): any;

export function StopSound(): any;

export function StopSoundMulti(): any;

export function SubText(): any;

export function TakeScreenshot(): any;

export function TextAppend(): any;

export function TextCopy(): any;

export function TextFindIndex(): any;

export function TextFormat(args: any): any;

export function TextInsert(): any;

export function TextIsEqual(): any;

export function TextJoin(): any;

export function TextLength(): any;

export function TextReplace(): any;

export function TextSplit(): any;

export function TextSubtext(): any;

export function TextToInteger(): any;

export function TextToLower(): any;

export function TextToPascal(): any;

export function TextToUpper(): any;

export function TextToUtf8(): any;

export function ToggleFullscreen(): any;

export function ToggleVrMode(): any;

export function TraceLog(logType: any, args: any): void;

export function TraceLogWrap(): any;

export function UnhideWindow(): any;

export function UnloadFont(): any;

export function UnloadImage(): any;

export function UnloadMusicStream(): any;

export function UnloadRenderTexture(): any;

export function UnloadShader(): any;

export function UnloadSound(): any;

export function UnloadTexture(): any;

export function UnloadWave(): any;

export function UpdateAudioStream(): any;

export function UpdateCamera(camera: any): void;

export function UpdateCameraWrap(): any;

export function UpdateMusicStream(): any;

export function UpdateSound(): any;

export function UpdateTexture(): any;

export function UpdateVrTracking(camera: any): void;

export function UpdateVrTrackingWrap(): any;

export function Vector2(x: any, y: any): any;

export function Vector2Add(): any;

export function Vector2AddValue(): any;

export function Vector2Angle(): any;

export function Vector2Distance(): any;

export function Vector2Divide(): any;

export function Vector2DotProduct(): any;

export function Vector2Length(): any;

export function Vector2Lerp(): any;

export function Vector2MoveTowards(): any;

export function Vector2Multiply(): any;

export function Vector2Negate(): any;

export function Vector2Normalize(): any;

export function Vector2One(): any;

export function Vector2Rotate(): any;

export function Vector2Scale(): any;

export function Vector2Subtract(): any;

export function Vector2SubtractValue(): any;

export function Vector2Zero(): any;

export function Vector3(x: any, y: any, z: any): any;

export function Vector3Add(): any;

export function Vector3AddValue(): any;

export function Vector3Barycenter(): any;

export function Vector3CrossProduct(): any;

export function Vector3Distance(): any;

export function Vector3Divide(): any;

export function Vector3DotProduct(): any;

export function Vector3Length(): any;

export function Vector3Lerp(): any;

export function Vector3Max(): any;

export function Vector3Min(): any;

export function Vector3Multiply(): any;

export function Vector3Negate(): any;

export function Vector3Normalize(): any;

export function Vector3One(): any;

export function Vector3OrthoNormalize(): any;

export function Vector3Perpendicular(): any;

export function Vector3Reflect(): any;

export function Vector3RotateByQuaternion(): any;

export function Vector3Scale(): any;

export function Vector3Subtract(): any;

export function Vector3SubtractValue(): any;

export function Vector3Transform(): any;

export function Vector3Zero(): any;

export function Vector4(x: any, y: any, z: any, w: any): any;

export function VrDeviceInfo(): any;

export function WaveCopy(): any;

export function WaveCrop(): any;

export function WaveFormat(): any;

export function WindowShouldClose(): any;

export function rlBegin(): any;

export function rlCheckBufferLimit(): any;

export function rlClearColor(): any;

export function rlClearScreenBuffers(): any;

export function rlColor3f(): any;

export function rlColor4f(): any;

export function rlColor4ub(): any;

export function rlDeleteBuffers(): any;

export function rlDeleteRenderTextures(): any;

export function rlDeleteShader(): any;

export function rlDeleteTextures(): any;

export function rlDeleteVertexArrays(): any;

export function rlDisableBackfaceCulling(): any;

export function rlDisableDepthTest(): any;

export function rlDisableRenderTexture(): any;

export function rlDisableScissorTest(): any;

export function rlDisableTexture(): any;

export function rlDisableWireMode(): any;

export function rlDrawMesh(): any;

export function rlEnableBackfaceCulling(): any;

export function rlEnableDepthTest(): any;

export function rlEnableRenderTexture(): any;

export function rlEnableScissorTest(): any;

export function rlEnableTexture(): any;

export function rlEnableWireMode(): any;

export function rlEnd(): any;

export function rlFrustum(): any;

export function rlGenerateMipmaps(): any;

export function rlGetGlTextureFormats(): any;

export function rlGetVersion(): any;

export function rlLoadAttribBuffer(): any;

export function rlLoadExtensions(): any;

export function rlLoadIdentity(): any;

export function rlLoadMesh(): any;

export function rlLoadRenderTexture(): any;

export function rlLoadTexture(): any;

export function rlLoadTextureCubemap(): any;

export function rlLoadTextureDepth(): any;

export function rlMatrixMode(): any;

export function rlMultMatrixf(): any;

export function rlNormal3f(): any;

export function rlOrtho(): any;

export function rlPopMatrix(): any;

export function rlPushMatrix(): any;

export function rlReadScreenPixels(): any;

export function rlReadTexturePixels(): any;

export function rlRenderTextureAttach(): any;

export function rlRenderTextureComplete(): any;

export function rlRotatef(): any;

export function rlScalef(): any;

export function rlScissor(): any;

export function rlSetDebugMarker(): any;

export function rlTexCoord2f(): any;

export function rlTextureParameters(): any;

export function rlTranslatef(): any;

export function rlUnloadMesh(): any;

export function rlUnloadTexture(): any;

export function rlUnproject(): any;

export function rlUpdateBuffer(): any;

export function rlUpdateMesh(): any;

export function rlUpdateMeshAt(): any;

export function rlUpdateTexture(): any;

export function rlVertex2f(): any;

export function rlVertex2i(): any;

export function rlVertex3f(): any;

export function rlViewport(): any;

export function rlglClose(): any;

export function rlglDraw(): any;

export function rlglInit(): any;

