"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var raylib_1 = __importDefault(require("./bindings/raylib"));
exports.InitAudioDevice = raylib_1.default.InitAudioDevice; //Initialize audio device and context 
exports.CloseAudioDevice = raylib_1.default.CloseAudioDevice; //Close the audio device and context (and music stream) 
exports.IsAudioDeviceReady = raylib_1.default.IsAudioDeviceReady; //Check if audio device is ready 
exports.SetMasterVolume = raylib_1.default.SetMasterVolume; //Set master volume (listener) 
exports.LoadWave = raylib_1.default.LoadWave; //Load wave data from file 
exports.LoadWaveEx = raylib_1.default.LoadWaveEx; //Load wave data from raw array data 
exports.LoadSound = raylib_1.default.LoadSound; //Load sound from file 
exports.LoadSoundFromWave = raylib_1.default.LoadSoundFromWave; //Load sound from wave data 
exports.UpdateSound = raylib_1.default.UpdateSound; //Update sound buffer with new data 
exports.UnloadWave = raylib_1.default.UnloadWave; //Unload wave data 
exports.UnloadSound = raylib_1.default.UnloadSound; //Unload sound 
exports.ExportWave = raylib_1.default.ExportWave; //Export wave data to file 
exports.ExportWaveAsCode = raylib_1.default.ExportWaveAsCode; //Export wave sample data to code (.h) 
exports.PlaySound = raylib_1.default.PlaySound; //Play a sound 
exports.PauseSound = raylib_1.default.PauseSound; //Pause a sound 
exports.ResumeSound = raylib_1.default.ResumeSound; //Resume a paused sound 
exports.StopSound = raylib_1.default.StopSound; //Stop playing a sound 
exports.IsSoundPlaying = raylib_1.default.IsSoundPlaying; //Check if a sound is currently playing 
exports.SetSoundVolume = raylib_1.default.SetSoundVolume; //Set volume for a sound (1.0 is max level) 
exports.SetSoundPitch = raylib_1.default.SetSoundPitch; //Set pitch for a sound (1.0 is base level) 
exports.WaveFormat = raylib_1.default.WaveFormat; //Convert wave data to desired format 
exports.WaveCopy = raylib_1.default.WaveCopy; //Copy a wave to a new wave 
exports.WaveCrop = raylib_1.default.WaveCrop; //Crop a wave to defined samples range 
exports.GetWaveData = raylib_1.default.GetWaveData; //Get samples data from wave as a floats array 
exports.LoadMusicStream = raylib_1.default.LoadMusicStream; //Load music stream from file 
exports.UnloadMusicStream = raylib_1.default.UnloadMusicStream; //Unload music stream 
exports.PlayMusicStream = raylib_1.default.PlayMusicStream; //Start music playing 
exports.UpdateMusicStream = raylib_1.default.UpdateMusicStream; //Updates buffers for music streaming 
exports.StopMusicStream = raylib_1.default.StopMusicStream; //Stop music playing 
exports.PauseMusicStream = raylib_1.default.PauseMusicStream; //Pause music playing 
exports.ResumeMusicStream = raylib_1.default.ResumeMusicStream; //Resume playing paused music 
exports.IsMusicPlaying = raylib_1.default.IsMusicPlaying; //Check if music is playing 
exports.SetMusicVolume = raylib_1.default.SetMusicVolume; //Set volume for music (1.0 is max level) 
exports.SetMusicPitch = raylib_1.default.SetMusicPitch; //Set pitch for a music (1.0 is base level) 
exports.SetMusicLoopCount = raylib_1.default.SetMusicLoopCount; //Set music loop count (loop repeats) 
exports.GetMusicTimeLength = raylib_1.default.GetMusicTimeLength; //Get music time length (in seconds) 
exports.GetMusicTimePlayed = raylib_1.default.GetMusicTimePlayed; //Get current music time played (in seconds) 
exports.InitAudioStream = raylib_1.default.InitAudioStream; //Init audio stream (to stream raw audio pcm data) 
exports.UpdateAudioStream = raylib_1.default.UpdateAudioStream; //Update audio stream buffers with data 
exports.CloseAudioStream = raylib_1.default.CloseAudioStream; //Close audio stream and free memory 
exports.IsAudioBufferProcessed = raylib_1.default.IsAudioBufferProcessed; //Check if any audio stream buffers requires refill 
exports.PlayAudioStream = raylib_1.default.PlayAudioStream; //Play audio stream 
exports.PauseAudioStream = raylib_1.default.PauseAudioStream; //Pause audio stream 
exports.ResumeAudioStream = raylib_1.default.ResumeAudioStream; //Resume audio stream 
exports.IsAudioStreamPlaying = raylib_1.default.IsAudioStreamPlaying; //Check if audio stream is playing 
exports.StopAudioStream = raylib_1.default.StopAudioStream; //Stop audio stream 
exports.SetAudioStreamVolume = raylib_1.default.SetAudioStreamVolume; //Set volume for audio stream (1.0 is max level) 
exports.SetAudioStreamPitch = raylib_1.default.SetAudioStreamPitch; //Set pitch for audio stream (1.0 is base level) 
