export declare class Color {
    r: number;
    g: number;
    b: number;
    a: number;
    constructor(red: number, green: number, blue: number, alpha: number);
}
export declare const LIGHTGRAY: Color;
export declare const GRAY: Color;
export declare const DARKGRAY: Color;
export declare const YELLOW: Color;
export declare const GOLD: Color;
export declare const ORANGE: Color;
export declare const PINK: Color;
export declare const RED: Color;
export declare const MAROON: Color;
export declare const GREEN: Color;
export declare const LIME: Color;
export declare const DARKGREEN: Color;
export declare const SKYBLUE: Color;
export declare const BLUE: Color;
export declare const DARKBLUE: Color;
export declare const PURPLE: Color;
export declare const VIOLET: Color;
export declare const DARKPURPLE: Color;
export declare const BEIGE: Color;
export declare const BROWN: Color;
export declare const DARKBROWN: Color;
export declare const WHITE: Color;
export declare const BLACK: Color;
export declare const BLANK: Color;
export declare const MAGENTA: Color;
export declare const RAYWHITE: Color;
