import { Color } from "./types/colors";
import { Vector2, Vector3, Ray } from "./types/maths";
import { Texture2D } from "./types/texture";
export declare const DrawLine3D: (startPos: Vector3, endPos: Vector3, color: Color) => void;
export declare const DrawCircle3D: (center: Vector3, radius: number, rotationAxis: Vector3, rotationAngle: number, color: Color) => void;
export declare const DrawCube: (position: Vector3, width: number, height: number, length: number, color: Color) => void;
export declare const DrawCubeV: (position: Vector3, size: Vector3, color: Color) => void;
export declare const DrawCubeWires: (position: Vector3, width: number, height: number, length: number, color: Color) => void;
export declare const DrawCubeWiresV: (position: Vector3, size: Vector3, color: Color) => void;
export declare const DrawCubeTexture: (texture: Texture2D, position: Vector3, width: number, height: number, length: number, color: Color) => void;
export declare const DrawSphere: (centerPos: Vector3, radius: number, color: Color) => void;
export declare const DrawSphereEx: (centerPos: Vector3, radius: number, rings: number, slices: number, color: Color) => void;
export declare const DrawSphereWires: (centerPos: Vector3, radius: number, rings: number, slices: number, color: Color) => void;
export declare const DrawCylinder: (position: Vector3, radiusTop: number, radiusBottom: number, height: number, slices: number, color: Color) => void;
export declare const DrawCylinderWires: (position: Vector3, radiusTop: number, radiusBottom: number, height: number, slices: number, color: Color) => void;
export declare const DrawPlane: (centerPos: Vector3, size: Vector2, color: Color) => void;
export declare const DrawRay: (ray: Ray, color: Color) => void;
export declare const DrawGrid: (slices: number, spacing: number) => void;
export declare const DrawGizmo: (position: Vector3) => void;
