import { Color } from "./types/colors";
import { Vector2, Rectangle } from "./types/maths";
import { Font, Image, CharInfo } from "./types/texture";
export declare const GetFontDefault: () => Font;
export declare const LoadFont: (fileName: string) => Font;
export declare const LoadFontEx: (fileName: string, fontSize: number, fontChars: number, charsCount: number) => Font;
export declare const LoadFontFromImage: (image: Image, key: Color, firstChar: number) => Font;
export declare const LoadFontData: (fileName: string, fontSize: number, fontChars: number, charsCount: number, type: number) => CharInfo;
export declare const GenImageFontAtlas: (chars: CharInfo, charsCount: number, fontSize: number, padding: number, packMethod: number) => Image;
export declare const UnloadFont: (font: Font) => void;
export declare const DrawFPS: (posX: number, posY: number) => void;
export declare const DrawText: (text: string, posX: number, posY: number, fontSize: number, color: Color) => void;
export declare const DrawTextEx: (font: Font, text: string, position: Vector2, fontSize: number, spacing: number, tint: Color) => void;
export declare const DrawTextRec: (font: Font, text: string, rec: Rectangle, fontSize: number, spacing: number, wordWrap: boolean, tint: Color) => void;
export declare const DrawTextRecEx: (font: Font, text: string, rec: Rectangle, fontSize: number, spacing: number, wordWrap: boolean, tint: Color, selectStart: number, selectLength: number, selectText: Color, selectBack: Color) => void;
export declare const MeasureText: (text: string, fontSize: number) => number;
export declare const MeasureTextEx: (font: Font, text: string, fontSize: number, spacing: number) => Vector2;
export declare const GetGlyphIndex: (font: Font, character: number) => number;
export declare const TextIsEqual: (text1: string, text2: string) => boolean;
export declare const TextLength: (text: string) => number;
export declare const TextFormat: (text: string, ...args: any) => string;
export declare const TextSubtext: (text: string, position: number, length: number) => string;
export declare const TextReplace: (text: string, replace: string, by: string) => string;
export declare const TextInsert: (text: string, insert: string, position: number) => string;
export declare const TextJoin: (textList: string, count: number, delimiter: string) => string;
export declare const TextSplit: (text: string, delimiter: string, count: number) => string;
export declare const TextAppend: (text: string, append: string, position: number) => void;
export declare const TextFindIndex: (text: string, find: string) => number;
export declare const TextToUpper: (text: string) => string;
export declare const TextToLower: (text: string) => string;
export declare const TextToPascal: (text: string) => string;
export declare const TextToInteger: (text: string) => number;
