/**
 * node-raylib
 *
 * https://github.com/robloach/node-raylib
 */
import r from "./src/bindings/raylib";
import * as colors from "./src/types/colors";
import * as camera from "./src/types/camera";
import * as maths from "./src/types/maths";
import * as shaders from "./src/shaders";
declare const raylib: {
    InitAudioDevice: () => void;
    CloseAudioDevice: () => void;
    IsAudioDeviceReady: () => boolean;
    SetMasterVolume: (volume: number) => void;
    LoadWave: (fileName: string) => any;
    LoadWaveEx: (data: void, sampleCount: number, sampleRate: number, sampleSize: number, channels: number) => any;
    LoadSound: (fileName: string) => any;
    LoadSoundFromWave: (wave: any) => any;
    UpdateSound: (sound: any, data: any, : any, samplesCount: number) => void;
    UnloadWave: (wave: any) => void;
    UnloadSound: (sound: any) => void;
    ExportWave: (wave: any, fileName: string) => void;
    ExportWaveAsCode: (wave: any, fileName: string) => void;
    PlaySound: (sound: any) => void;
    PauseSound: (sound: any) => void;
    ResumeSound: (sound: any) => void;
    StopSound: (sound: any) => void;
    IsSoundPlaying: (sound: any) => boolean;
    SetSoundVolume: (sound: any, volume: number) => void;
    SetSoundPitch: (sound: any, pitch: number) => void;
    WaveFormat: (wave: any, sampleRate: number, sampleSize: number, channels: number) => void;
    WaveCopy: (wave: any) => any;
    WaveCrop: (wave: any, initSample: number, finalSample: number) => void;
    GetWaveData: (wave: any) => any;
    LoadMusicStream: (fileName: string) => any;
    UnloadMusicStream: (music: any) => void;
    PlayMusicStream: (music: any) => void;
    UpdateMusicStream: (music: any) => void;
    StopMusicStream: (music: any) => void;
    PauseMusicStream: (music: any) => void;
    ResumeMusicStream: (music: any) => void;
    IsMusicPlaying: (music: any) => boolean;
    SetMusicVolume: (music: any, volume: number) => void;
    SetMusicPitch: (music: any, pitch: number) => void;
    SetMusicLoopCount: (music: any, count: number) => void;
    GetMusicTimeLength: (music: any) => number;
    GetMusicTimePlayed: (music: any) => number;
    InitAudioStream: (sampleRate: number, sampleSize: number, channels: number) => any;
    UpdateAudioStream: (stream: any, data: any, : any, samplesCount: number) => void;
    CloseAudioStream: (stream: any) => void;
    IsAudioBufferProcessed: (stream: any) => boolean;
    PlayAudioStream: (stream: any) => void;
    PauseAudioStream: (stream: any) => void;
    ResumeAudioStream: (stream: any) => void;
    IsAudioStreamPlaying: (stream: any) => boolean;
    StopAudioStream: (stream: any) => void;
    SetAudioStreamVolume: (stream: any, volume: number) => void;
    SetAudioStreamPitch: (stream: any, pitch: number) => void;
    Shader: typeof shaders.Shader;
    LoadText: (fileName: string) => string;
    LoadShader: (vsFileName: string, fsFileName: string) => shaders.Shader;
    LoadShaderCode: (vsCode: string, fsCode: string) => shaders.Shader;
    UnloadShader: (shader: shaders.Shader) => void;
    GetShaderDefault: () => shaders.Shader;
    GetTextureDefault: () => any;
    GetShaderLocation: (shader: shaders.Shader, uniformName: string) => number;
    SetShaderValue: (shader: shaders.Shader, uniformLoc: number, value: any, : any, uniformType: number) => void;
    SetShaderValueV: (shader: shaders.Shader, uniformLoc: number, value: any, : any, uniformType: number, count: number) => void;
    SetShaderValueMatrix: (shader: shaders.Shader, uniformLoc: number, mat: any) => void;
    SetShaderValueTexture: (shader: shaders.Shader, uniformLoc: number, texture: any) => void;
    SetMatrixProjection: (proj: any) => void;
    SetMatrixModelview: (view: any) => void;
    GetMatrixModelview: any;
    BeginShaderMode: (shader: shaders.Shader) => void;
    EndShaderMode: () => void;
    BeginBlendMode: (mode: number) => void;
    EndBlendMode: () => void;
    BeginScissorMode: (x: number, y: number, width: number, height: number) => void;
    EndScissorMode: () => void;
    InitVrSimulator: () => void;
    CloseVrSimulator: () => void;
    UpdateVrTracking: (camera: camera.Camera3D) => void;
    SetVrConfiguration: (info: any, distortion: shaders.Shader) => void;
    IsVrSimulatorReady: () => boolean;
    ToggleVrMode: () => void;
    BeginVrDrawing: () => void;
    EndVrDrawing: () => void;
    DrawLine3D: (startPos: maths.Vector3, endPos: maths.Vector3, color: colors.Color) => void;
    DrawCircle3D: (center: maths.Vector3, radius: number, rotationAxis: maths.Vector3, rotationAngle: number, color: colors.Color) => void;
    DrawCube: (position: maths.Vector3, width: number, height: number, length: number, color: colors.Color) => void;
    DrawCubeV: (position: maths.Vector3, size: maths.Vector3, color: colors.Color) => void;
    DrawCubeWires: (position: maths.Vector3, width: number, height: number, length: number, color: colors.Color) => void;
    DrawCubeWiresV: (position: maths.Vector3, size: maths.Vector3, color: colors.Color) => void;
    DrawCubeTexture: (texture: any, position: maths.Vector3, width: number, height: number, length: number, color: colors.Color) => void;
    DrawSphere: (centerPos: maths.Vector3, radius: number, color: colors.Color) => void;
    DrawSphereEx: (centerPos: maths.Vector3, radius: number, rings: number, slices: number, color: colors.Color) => void;
    DrawSphereWires: (centerPos: maths.Vector3, radius: number, rings: number, slices: number, color: colors.Color) => void;
    DrawCylinder: (position: maths.Vector3, radiusTop: number, radiusBottom: number, height: number, slices: number, color: colors.Color) => void;
    DrawCylinderWires: (position: maths.Vector3, radiusTop: number, radiusBottom: number, height: number, slices: number, color: colors.Color) => void;
    DrawPlane: (centerPos: maths.Vector3, size: any, color: colors.Color) => void;
    DrawRay: (ray: any, color: colors.Color) => void;
    DrawGrid: (slices: number, spacing: number) => void;
    DrawGizmo: (position: maths.Vector3) => void;
    LoadModel: (fileName: string) => any;
    LoadModelFromMesh: (mesh: any) => any;
    UnloadModel: (model: any) => void;
    LoadMeshes: (fileName: string, meshCount: number) => any;
    ExportMesh: (mesh: any, fileName: string) => void;
    UnloadMesh: (mesh: any) => void;
    LoadMaterials: (fileName: string, materialCount: number) => any;
    LoadMaterialDefault: () => any;
    UnloadMaterial: (material: any) => void;
    SetMaterialTexture: (material: any, mapType: number, texture: any) => void;
    SetModelMeshMaterial: (model: any, meshId: number, materialId: number) => void;
    LoadModelAnimations: (fileName: string, animsCount: number) => any;
    UpdateModelAnimation: (model: any, anim: any, frame: number) => void;
    UnloadModelAnimation: (anim: any) => void;
    IsModelAnimationValid: (model: any, anim: any) => boolean;
    GenMeshPoly: (sides: number, radius: number) => any;
    GenMeshPlane: (width: number, length: number, resX: number, resZ: number) => any;
    GenMeshCube: (width: number, height: number, length: number) => any;
    GenMeshSphere: (radius: number, rings: number, slices: number) => any;
    GenMeshHemiSphere: (radius: number, rings: number, slices: number) => any;
    GenMeshCylinder: (radius: number, height: number, slices: number) => any;
    GenMeshTorus: (radius: number, size: number, radSeg: number, sides: number) => any;
    GenMeshKnot: (radius: number, size: number, radSeg: number, sides: number) => any;
    GenMeshHeightmap: (heightmap: any, size: maths.Vector3) => any;
    GenMeshCubicmap: (cubicmap: any, cubeSize: maths.Vector3) => any;
    MeshBoundingBox: (mesh: any) => any;
    MeshTangents: (mesh: any) => void;
    MeshBinormals: (mesh: any) => void;
    DrawModel: (model: any, position: maths.Vector3, scale: number, tint: colors.Color) => void;
    DrawModelEx: (model: any, position: maths.Vector3, rotationAxis: maths.Vector3, rotationAngle: number, scale: maths.Vector3, tint: colors.Color) => void;
    DrawModelWires: (model: any, position: maths.Vector3, scale: number, tint: colors.Color) => void;
    DrawModelWiresEx: (model: any, position: maths.Vector3, rotationAxis: maths.Vector3, rotationAngle: number, scale: maths.Vector3, tint: colors.Color) => void;
    DrawBoundingBox: (box: any, color: colors.Color) => void;
    DrawBillboard: (camera: any, texture: any, center: maths.Vector3, size: number, tint: colors.Color) => void;
    DrawBillboardRec: (camera: any, texture: any, sourceRec: any, center: maths.Vector3, size: number, tint: colors.Color) => void;
    CheckCollisionSpheres: (centerA: maths.Vector3, radiusA: number, centerB: maths.Vector3, radiusB: number) => boolean;
    CheckCollisionBoxes: (box1: any, box2: any) => boolean;
    CheckCollisionBoxSphere: (box: any, centerSphere: maths.Vector3, radiusSphere: number) => boolean;
    CheckCollisionRaySphere: (ray: any, spherePosition: maths.Vector3, sphereRadius: number) => boolean;
    CheckCollisionRaySphereEx: (ray: any, spherePosition: maths.Vector3, sphereRadius: number, collisionPoint: maths.Vector3) => boolean;
    CheckCollisionRayBox: (ray: any, box: any) => boolean;
    GetCollisionRayModel: (ray: any, model: any) => any;
    GetCollisionRayTriangle: (ray: any, p1: maths.Vector3, p2: maths.Vector3, p3: maths.Vector3) => any;
    GetCollisionRayGround: (ray: any, groundHeight: number) => any;
    GetFontDefault: () => any;
    LoadFont: (fileName: string) => any;
    LoadFontEx: (fileName: string, fontSize: number, fontChars: number, charsCount: number) => any;
    LoadFontFromImage: (image: any, key: colors.Color, firstChar: number) => any;
    LoadFontData: (fileName: string, fontSize: number, fontChars: number, charsCount: number, type: number) => any;
    GenImageFontAtlas: (chars: any, charsCount: number, fontSize: number, padding: number, packMethod: number) => any;
    UnloadFont: (font: any) => void;
    DrawFPS: (posX: number, posY: number) => void;
    DrawText: (text: string, posX: number, posY: number, fontSize: number, color: colors.Color) => void;
    DrawTextEx: (font: any, text: string, position: maths.Vector2, fontSize: number, spacing: number, tint: colors.Color) => void;
    DrawTextRec: (font: any, text: string, rec: any, fontSize: number, spacing: number, wordWrap: boolean, tint: colors.Color) => void;
    DrawTextRecEx: (font: any, text: string, rec: any, fontSize: number, spacing: number, wordWrap: boolean, tint: colors.Color, selectStart: number, selectLength: number, selectText: colors.Color, selectBack: colors.Color) => void;
    MeasureText: (text: string, fontSize: number) => number;
    MeasureTextEx: (font: any, text: string, fontSize: number, spacing: number) => maths.Vector2;
    GetGlyphIndex: (font: any, character: number) => number;
    TextIsEqual: (text1: string, text2: string) => boolean;
    TextLength: (text: string) => number;
    TextFormat: (text: string, ...: any) => string;
    TextSubtext: (text: string, position: number, length: number) => string;
    TextReplace: (text: string, replace: string, by: string) => string;
    TextInsert: (text: string, insert: string, position: number) => string;
    TextJoin: (textList: any, char: any, : any, count: number, delimiter: string) => string;
    TextSplit: (text: string, delimiter: string, count: number) => any;
    char: any;
    TextAppend: (text: string, append: string, position: number) => void;
    TextFindIndex: (text: string, find: string) => number;
    TextToUpper: (text: string) => string;
    TextToLower: (text: string) => string;
    TextToPascal: (text: string) => string;
    TextToInteger: (text: string) => number;
    LoadImage: (fileName: string) => any;
    LoadImageEx: (pixels: colors.Color, width: number, height: number) => any;
    LoadImagePro: (data: void, width: number, height: number, format: number) => any;
    LoadImageRaw: (fileName: string, width: number, height: number, format: number, headerSize: number) => any;
    ExportImage: (image: any, fileName: string) => void;
    ExportImageAsCode: (image: any, fileName: string) => void;
    LoadTexture: (fileName: string) => any;
    LoadTextureFromImage: (image: any) => any;
    LoadTextureCubemap: (image: any, layoutType: number) => any;
    LoadRenderTexture: (width: number, height: number) => any;
    UnloadImage: (image: any) => void;
    UnloadTexture: (texture: any) => void;
    UnloadRenderTexture: (target: any) => void;
    GetImageData: (image: any) => colors.Color;
    GetImageDataNormalized: (image: any) => any;
    GetPixelDataSize: (width: number, height: number, format: number) => number;
    GetTextureData: (texture: any) => any;
    GetScreenData: () => any;
    UpdateTexture: (texture: any, pixels: any, : any) => void;
    ImageCopy: (image: any) => any;
    ImageToPOT: (image: any, fillColor: colors.Color) => void;
    ImageFormat: (image: any, newFormat: number) => void;
    ImageAlphaMask: (image: any, alphaMask: any) => void;
    ImageAlphaClear: (image: any, color: colors.Color, threshold: number) => void;
    ImageAlphaCrop: (image: any, threshold: number) => void;
    ImageAlphaPremultiply: (image: any) => void;
    ImageCrop: (image: any, crop: any) => void;
    ImageResize: (image: any, newWidth: number, newHeight: number) => void;
    ImageResizeNN: (image: any, newHeight: any, newWidth: any, int: any) => void;
    ImageResizeCanvas: (image: any, newWidth: number, newHeight: number, offsetX: number, offsetY: number, color: colors.Color) => void;
    ImageMipmaps: (image: any) => void;
    ImageDither: (image: any, rBpp: number, gBpp: number, bBpp: number, aBpp: number) => void;
    ImageExtractPalette: (image: any, maxPaletteSize: number, extractCount: number) => colors.Color;
    ImageText: (text: string, fontSize: number, color: colors.Color) => any;
    ImageTextEx: (font: any, text: string, fontSize: number, spacing: number, tint: colors.Color) => any;
    ImageDraw: (dst: any, src: any, srcRec: any, dstRec: any) => void;
    ImageDrawRectangle: (dst: any, rec: any, color: colors.Color) => void;
    ImageDrawRectangleLines: (dst: any, rec: any, thick: number, color: colors.Color) => void;
    ImageDrawText: (dst: any, position: any, text: string, fontSize: number, color: colors.Color) => void;
    ImageDrawTextEx: (dst: any, position: any, font: any, text: string, fontSize: number, spacing: number, color: colors.Color) => void;
    ImageFlipVertical: (image: any) => void;
    ImageFlipHorizontal: (image: any) => void;
    ImageRotateCW: (image: any) => void;
    ImageRotateCCW: (image: any) => void;
    ImageColorTint: (image: any, color: colors.Color) => void;
    ImageColorInvert: (image: any) => void;
    ImageColorGrayscale: (image: any) => void;
    ImageColorContrast: (image: any, contrast: number) => void;
    ImageColorBrightness: (image: any, brightness: number) => void;
    ImageColorReplace: (image: any, color: colors.Color, replace: colors.Color) => void;
    GenImageColor: (width: number, height: number, color: colors.Color) => any;
    GenImageGradientV: (width: number, height: number, top: colors.Color, bottom: colors.Color) => any;
    GenImageGradientH: (width: number, height: number, left: colors.Color, right: colors.Color) => any;
    GenImageGradientRadial: (width: number, height: number, density: number, inner: colors.Color, outer: colors.Color) => any;
    GenImageChecked: (width: number, height: number, checksX: number, checksY: number, col1: colors.Color, col2: colors.Color) => any;
    GenImageWhiteNoise: (width: number, height: number, factor: number) => any;
    GenImagePerlinNoise: (width: number, height: number, offsetX: number, offsetY: number, scale: number) => any;
    GenImageCellular: (width: number, height: number, tileSize: number) => any;
    GenTextureMipmaps: (texture: any) => void;
    SetTextureFilter: (texture: any, filterMode: number) => void;
    SetTextureWrap: (texture: any, wrapMode: number) => void;
    DrawTexture: (texture: any, posX: number, posY: number, tint: colors.Color) => void;
    DrawTextureV: (texture: any, position: any, tint: colors.Color) => void;
    DrawTextureEx: (texture: any, position: any, rotation: number, scale: number, tint: colors.Color) => void;
    DrawTextureRec: (texture: any, sourceRec: any, position: any, tint: colors.Color) => void;
    DrawTextureQuad: (texture: any, tiling: any, offset: any, quad: any, tint: colors.Color) => void;
    DrawTexturePro: (texture: any, sourceRec: any, destRec: any, origin: any, rotation: number, tint: colors.Color) => void;
    DrawTextureNPatch: (texture: any, nPatchInfo: any, destRec: any, origin: any, rotation: number, tint: colors.Color) => void;
    DrawPixel: (posX: number, posY: number, color: colors.Color) => void;
    DrawPixelV: (position: maths.Vector2, color: colors.Color) => void;
    DrawLine: (startPosX: number, startPosY: number, endPosX: number, endPosY: number, color: colors.Color) => void;
    DrawLineV: (startPos: maths.Vector2, endPos: maths.Vector2, color: colors.Color) => void;
    DrawLineEx: (startPos: maths.Vector2, endPos: maths.Vector2, thick: number, color: colors.Color) => void;
    DrawLineBezier: (startPos: maths.Vector2, endPos: maths.Vector2, thick: number, color: colors.Color) => void;
    DrawLineStrip: (points: maths.Vector2, numPoints: number, color: colors.Color) => void;
    DrawCircle: (centerX: number, centerY: number, radius: number, color: colors.Color) => void;
    DrawCircleSector: (center: maths.Vector2, radius: number, startAngle: number, endAngle: number, segments: number, color: colors.Color) => void;
    DrawCircleSectorLines: (center: maths.Vector2, radius: number, startAngle: number, endAngle: number, segments: number, color: colors.Color) => void;
    DrawCircleGradient: (centerX: number, centerY: number, radius: number, color1: colors.Color, color2: colors.Color) => void;
    DrawCircleV: (center: maths.Vector2, radius: number, color: colors.Color) => void;
    DrawCircleLines: (centerX: number, centerY: number, radius: number, color: colors.Color) => void;
    DrawRing: (center: maths.Vector2, innerRadius: number, outerRadius: number, startAngle: number, endAngle: number, segments: number, color: colors.Color) => void;
    DrawRingLines: (center: maths.Vector2, innerRadius: number, outerRadius: number, startAngle: number, endAngle: number, segments: number, color: colors.Color) => void;
    DrawRectangle: (posX: number, posY: number, width: number, height: number, color: colors.Color) => void;
    DrawRectangleV: (position: maths.Vector2, size: maths.Vector2, color: colors.Color) => void;
    DrawRectangleRec: (rec: any, color: colors.Color) => void;
    DrawRectanglePro: (rec: any, origin: maths.Vector2, rotation: number, color: colors.Color) => void;
    DrawRectangleGradientV: (posX: number, posY: number, width: number, height: number, color1: colors.Color, color2: colors.Color) => void;
    DrawRectangleGradientH: (posX: number, posY: number, width: number, height: number, color1: colors.Color, color2: colors.Color) => void;
    DrawRectangleGradientEx: (rec: any, col1: colors.Color, col2: colors.Color, col3: colors.Color, col4: colors.Color) => void;
    DrawRectangleLines: (posX: number, posY: number, width: number, height: number, color: colors.Color) => void;
    DrawRectangleLinesEx: (rec: any, lineThick: number, color: colors.Color) => void;
    DrawRectangleRounded: (rec: any, roundness: number, segments: number, color: colors.Color) => void;
    DrawRectangleRoundedLines: (rec: any, roundness: number, segments: number, lineThick: number, color: colors.Color) => void;
    DrawTriangle: (v1: maths.Vector2, v2: maths.Vector2, v3: maths.Vector2, color: colors.Color) => void;
    DrawTriangleLines: (v1: maths.Vector2, v2: maths.Vector2, v3: maths.Vector2, color: colors.Color) => void;
    DrawTriangleFan: (points: maths.Vector2, numPoints: number, color: colors.Color) => void;
    DrawPoly: (center: maths.Vector2, sides: number, radius: number, rotation: number, color: colors.Color) => void;
    SetShapesTexture: (texture: any, source: any) => void;
    CheckCollisionRecs: (rec1: any, rec2: any) => boolean;
    CheckCollisionCircles: (center1: maths.Vector2, radius1: number, center2: maths.Vector2, radius2: number) => boolean;
    CheckCollisionCircleRec: (center: maths.Vector2, radius: number, rec: any) => boolean;
    GetCollisionRec: (rec1: any, rec2: any) => any;
    CheckCollisionPointRec: (point: maths.Vector2, rec: any) => boolean;
    CheckCollisionPointCircle: (point: maths.Vector2, center: maths.Vector2, radius: number) => boolean;
    CheckCollisionPointTriangle: (point: maths.Vector2, p1: maths.Vector2, p2: maths.Vector2, p3: maths.Vector2) => boolean;
    InitWindow: (width: number, height: number, title: string) => void;
    WindowShouldClose: () => boolean;
    CloseWindow: () => void;
    IsWindowReady: () => boolean;
    IsWindowMinimized: () => boolean;
    IsWindowResized: () => boolean;
    IsWindowHidden: () => boolean;
    ToggleFullscreen: () => void;
    UnhideWindow: () => void;
    HideWindow: () => void;
    SetWindowIcon: (image: any) => void;
    SetWindowTitle: (title: string) => void;
    SetWindowPosition: (x: number, y: number) => void;
    SetWindowMonitor: (monitor: number) => void;
    SetWindowMinSize: (width: number, height: number) => void;
    SetWindowSize: (width: number, height: number) => void;
    GetWindowHandle: () => void;
    GetScreenWidth: () => number;
    GetScreenHeight: () => number;
    GetMonitorCount: () => number;
    GetMonitorWidth: (monitor: number) => number;
    GetMonitorHeight: (monitor: number) => number;
    GetMonitorPhysicalWidth: (monitor: number) => number;
    GetMonitorPhysicalHeight: (monitor: number) => number;
    GetMonitorName: (monitor: number) => string;
    GetClipboardText: () => string;
    SetClipboardText: (text: string) => void;
    ShowCursor: () => void;
    HideCursor: () => void;
    IsCursorHidden: () => boolean;
    EnableCursor: () => void;
    DisableCursor: () => void;
    ClearBackground: (color: colors.Color) => void;
    BeginDrawing: () => void;
    EndDrawing: () => void;
    BeginMode2D: (camera: camera.Camera2D) => void;
    EndMode2D: () => void;
    BeginMode3D: (camera: camera.Camera3D) => void;
    EndMode3D: () => void;
    BeginTextureMode: (target: any) => void;
    EndTextureMode: () => void;
    GetMouseRay: (mousePosition: maths.Vector2, camera: camera.Camera3D) => any;
    GetWorldToScreen: (position: maths.Vector3, camera: camera.Camera3D) => maths.Vector2;
    GetCameraMatrix: (camera: camera.Camera3D) => any;
    SetTargetFPS: (fps: number) => void;
    GetFPS: () => number;
    GetFrameTime: () => number;
    GetTime: () => number;
    ColorToInt: (color: colors.Color) => number;
    ColorNormalize: (color: colors.Color) => maths.Vector4;
    ColorToHSV: (color: colors.Color) => maths.Vector3;
    ColorFromHSV: (hsv: maths.Vector3) => colors.Color;
    GetColor: (hexValue: number) => colors.Color;
    Fade: (color: colors.Color, alpha: number) => colors.Color;
    SetConfigFlags: (flags: number) => void;
    SetTraceLogLevel: (logType: number) => void;
    SetTraceLogExit: (logType: number) => void;
    SetTraceLogCallback: (callback: any) => void;
    TraceLog: (logType: number, text: string, ...: any) => void;
    TakeScreenshot: (fileName: string) => void;
    GetRandomValue: (min: number, max: number) => number;
    FileExists: (fileName: string) => boolean;
    IsFileExtension: (fileName: string, ext: string) => boolean;
    GetExtension: (fileName: string) => string;
    GetFileName: (filePath: string) => string;
    GetFileNameWithoutExt: (filePath: string) => string;
    GetDirectoryPath: (fileName: string) => string;
    GetWorkingDirectory: () => string;
    GetDirectoryFiles: (dirPath: string, count: number) => number;
    ClearDirectoryFiles: () => void;
    ChangeDirectory: (dir: string) => boolean;
    IsFileDropped: () => boolean;
    GetDroppedFiles: (count: number) => number;
    ClearDroppedFiles: () => void;
    GetFileModTime: (fileName: string) => number;
    StorageSaveValue: (position: number, value: number) => void;
    StorageLoadValue: (position: number) => number;
    OpenURL: (url: string) => void;
    IsKeyPressed: (key: number) => boolean;
    IsKeyDown: (key: number) => boolean;
    IsKeyReleased: (key: number) => boolean;
    IsKeyUp: (key: number) => boolean;
    GetKeyPressed: () => number;
    SetExitKey: (key: number) => void;
    IsGamepadAvailable: (gamepad: number) => boolean;
    IsGamepadName: (gamepad: number, name: string) => boolean;
    GetGamepadName: (gamepad: number) => string;
    IsGamepadButtonPressed: (gamepad: number, button: number) => boolean;
    IsGamepadButtonDown: (gamepad: number, button: number) => boolean;
    IsGamepadButtonReleased: (gamepad: number, button: number) => boolean;
    IsGamepadButtonUp: (gamepad: number, button: number) => boolean;
    GetGamepadButtonPressed: () => number;
    GetGamepadAxisCount: (gamepad: number) => number;
    GetGamepadAxisMovement: (gamepad: number, axis: number) => number;
    IsMouseButtonPressed: (button: number) => boolean;
    IsMouseButtonDown: (button: number) => boolean;
    IsMouseButtonReleased: (button: number) => boolean;
    IsMouseButtonUp: (button: number) => boolean;
    GetMouseX: () => number;
    GetMouseY: () => number;
    GetMousePosition: () => maths.Vector2;
    SetMousePosition: (x: number, y: number) => void;
    SetMouseOffset: (offsetX: number, offsetY: number) => void;
    SetMouseScale: (scaleX: number, scaleY: number) => void;
    GetMouseWheelMove: () => number;
    GetTouchX: () => number;
    GetTouchY: () => number;
    GetTouchPosition: (index: number) => maths.Vector2;
    SetGesturesEnabled: (gestureFlags: number) => void;
    IsGestureDetected: (gesture: number) => boolean;
    GetGestureDetected: () => number;
    GetTouchPointsCount: () => number;
    GetGestureHoldDuration: () => number;
    GetGestureDragVector: () => maths.Vector2;
    GetGestureDragAngle: () => number;
    GetGesturePinchVector: () => maths.Vector2;
    GetGesturePinchAngle: () => number;
    SetCameraMode: (camera: camera.Camera3D, mode: number) => void;
    UpdateCamera: (camera: camera.Camera3D) => void;
    SetCameraPanControl: (panKey: number) => void;
    SetCameraAltControl: (altKey: number) => void;
    SetCameraSmoothZoomControl: (szKey: number) => void;
    SetCameraMoveControls: (frontKey: number, backKey: number, rightKey: number, leftKey: number, upKey: number, downKey: number) => void;
    /**
     * node-raylib
     *
     * https://github.com/robloach/node-raylib
     */
    Vector2: typeof maths.Vector2;
    Vector3: typeof maths.Vector3;
    Vector4: typeof maths.Vector4;
    Rectangle: typeof maths.Rectangle;
    Ray: typeof maths.Ray;
    RayHitInfo: typeof maths.RayHitInfo;
    Camera3D: typeof camera.Camera3D;
    Camera2D: typeof camera.Camera2D;
    /**
     * node-raylib
     *
     * https://github.com/robloach/node-raylib
     */
    Color: typeof colors.Color;
    LIGHTGRAY: colors.Color;
    GRAY: colors.Color;
    DARKGRAY: colors.Color;
    YELLOW: colors.Color;
    GOLD: colors.Color;
    ORANGE: colors.Color;
    PINK: colors.Color;
    RED: colors.Color;
    MAROON: colors.Color;
    GREEN: colors.Color;
    LIME: colors.Color;
    DARKGREEN: colors.Color;
    SKYBLUE: colors.Color;
    BLUE: colors.Color;
    DARKBLUE: colors.Color;
    PURPLE: colors.Color;
    VIOLET: colors.Color;
    DARKPURPLE: colors.Color;
    BEIGE: colors.Color;
    BROWN: colors.Color;
    DARKBROWN: colors.Color;
    WHITE: colors.Color;
    BLACK: colors.Color;
    BLANK: colors.Color;
    MAGENTA: colors.Color;
    RAYWHITE: colors.Color;
    PI: number;
    MAX_TOUCH_POINTS: number;
    MAX_SHADER_LOCATIONS: number;
    MAX_MATERIAL_MAPS: number;
    DEG2RAD: number;
    RAD2DEG: number;
};
export default raylib;
export { r };
