#ifndef NODE_RAYLIB_NODE_RAYLIB_H
#define NODE_RAYLIB_NODE_RAYLIB_H

#include <string>
#include <napi.h>

#include "raylib.h"
#include "lib/AddFunction.h"

void node_raylib_bindings(Napi::Env& env, Napi::Object& exports) {
  AddFunction(env, exports, "InitWindow", InitWindow);
  AddFunction(env, exports, "WindowShouldClose", WindowShouldClose);
  AddFunction(env, exports, "CloseWindow", CloseWindow);
  AddFunction(env, exports, "IsWindowReady", IsWindowReady);
  AddFunction(env, exports, "IsWindowMinimized", IsWindowMinimized);
  AddFunction(env, exports, "IsWindowFocused", IsWindowFocused);
  AddFunction(env, exports, "IsWindowResized", IsWindowResized);
  AddFunction(env, exports, "IsWindowHidden", IsWindowHidden);
  AddFunction(env, exports, "IsWindowFullscreen", IsWindowFullscreen);
  AddFunction(env, exports, "ToggleFullscreen", ToggleFullscreen);
  AddFunction(env, exports, "UnhideWindow", UnhideWindow);
  AddFunction(env, exports, "HideWindow", HideWindow);
  AddFunction(env, exports, "SetWindowIcon", SetWindowIcon);
  AddFunction(env, exports, "SetWindowTitle", SetWindowTitle);
  AddFunction(env, exports, "SetWindowPosition", SetWindowPosition);
  AddFunction(env, exports, "SetWindowMonitor", SetWindowMonitor);
  AddFunction(env, exports, "SetWindowMinSize", SetWindowMinSize);
  AddFunction(env, exports, "SetWindowSize", SetWindowSize);
  AddFunction(env, exports, "GetWindowHandle", GetWindowHandle);
  AddFunction(env, exports, "GetScreenWidth", GetScreenWidth);
  AddFunction(env, exports, "GetScreenHeight", GetScreenHeight);
  AddFunction(env, exports, "GetMonitorCount", GetMonitorCount);
  AddFunction(env, exports, "GetMonitorWidth", GetMonitorWidth);
  AddFunction(env, exports, "GetMonitorHeight", GetMonitorHeight);
  AddFunction(env, exports, "GetMonitorPhysicalWidth", GetMonitorPhysicalWidth);
  AddFunction(env, exports, "GetMonitorPhysicalHeight", GetMonitorPhysicalHeight);
  AddFunction(env, exports, "GetWindowPosition", GetWindowPosition);
  AddFunction(env, exports, "GetWindowScaleDPI", GetWindowScaleDPI);
  AddFunction(env, exports, "GetMonitorName", GetMonitorName);
  AddFunction(env, exports, "GetClipboardText", GetClipboardText);
  AddFunction(env, exports, "SetClipboardText", SetClipboardText);
  AddFunction(env, exports, "ShowCursor", ShowCursor);
  AddFunction(env, exports, "HideCursor", HideCursor);
  AddFunction(env, exports, "IsCursorHidden", IsCursorHidden);
  AddFunction(env, exports, "EnableCursor", EnableCursor);
  AddFunction(env, exports, "DisableCursor", DisableCursor);
  AddFunction(env, exports, "ClearBackground", ClearBackground);
  AddFunction(env, exports, "BeginDrawing", BeginDrawing);
  AddFunction(env, exports, "EndDrawing", EndDrawing);
  AddFunction(env, exports, "BeginMode2D", BeginMode2D);
  AddFunction(env, exports, "EndMode2D", EndMode2D);
  AddFunction(env, exports, "BeginMode3D", BeginMode3D);
  AddFunction(env, exports, "EndMode3D", EndMode3D);
  AddFunction(env, exports, "BeginTextureMode", BeginTextureMode);
  AddFunction(env, exports, "EndTextureMode", EndTextureMode);
  AddFunction(env, exports, "BeginScissorMode", BeginScissorMode);
  AddFunction(env, exports, "EndScissorMode", EndScissorMode);
  AddFunction(env, exports, "GetMouseRay", GetMouseRay);
  AddFunction(env, exports, "GetCameraMatrix", GetCameraMatrix);
  AddFunction(env, exports, "GetCameraMatrix2D", GetCameraMatrix2D);
  AddFunction(env, exports, "GetWorldToScreen", GetWorldToScreen);
  AddFunction(env, exports, "GetWorldToScreenEx", GetWorldToScreenEx);
  AddFunction(env, exports, "GetWorldToScreen2D", GetWorldToScreen2D);
  AddFunction(env, exports, "GetScreenToWorld2D", GetScreenToWorld2D);
  AddFunction(env, exports, "SetTargetFPS", SetTargetFPS);
  AddFunction(env, exports, "GetFPS", GetFPS);
  AddFunction(env, exports, "GetFrameTime", GetFrameTime);
  AddFunction(env, exports, "GetTime", GetTime);
  AddFunction(env, exports, "ColorToInt", ColorToInt);
  AddFunction(env, exports, "ColorNormalize", ColorNormalize);
  AddFunction(env, exports, "ColorFromNormalized", ColorFromNormalized);
  AddFunction(env, exports, "ColorToHSV", ColorToHSV);
  AddFunction(env, exports, "ColorFromHSV", ColorFromHSV);
  AddFunction(env, exports, "GetColor", GetColor);
  AddFunction(env, exports, "Fade", Fade);
  AddFunction(env, exports, "SetConfigFlags", SetConfigFlags);
  AddFunction(env, exports, "SetTraceLogLevel", SetTraceLogLevel);
  AddFunction(env, exports, "SetTraceLogExit", SetTraceLogExit);
  // AddFunction(env, exports, "SetTraceLogCallback", SetTraceLogCallback);
  // AddFunction(env, exports, "TraceLog", TraceLog);
  AddFunction(env, exports, "TakeScreenshot", TakeScreenshot);
  AddFunction(env, exports, "GetRandomValue", GetRandomValue);
  AddFunction(env, exports, "LoadFileData", LoadFileData);
  AddFunction(env, exports, "SaveFileData", SaveFileData);
  AddFunction(env, exports, "LoadFileText", LoadFileText);
  AddFunction(env, exports, "SaveFileText", SaveFileText);
  AddFunction(env, exports, "FileExists", FileExists);
  AddFunction(env, exports, "IsFileExtension", IsFileExtension);
  AddFunction(env, exports, "DirectoryExists", DirectoryExists);
  AddFunction(env, exports, "GetExtension", GetExtension);
  AddFunction(env, exports, "GetFileName", GetFileName);
  AddFunction(env, exports, "GetFileNameWithoutExt", GetFileNameWithoutExt);
  AddFunction(env, exports, "GetDirectoryPath", GetDirectoryPath);
  AddFunction(env, exports, "GetPrevDirectoryPath", GetPrevDirectoryPath);
  AddFunction(env, exports, "GetWorkingDirectory", GetWorkingDirectory);
  AddFunction(env, exports, "GetDirectoryFiles", GetDirectoryFiles);
  AddFunction(env, exports, "ClearDirectoryFiles", ClearDirectoryFiles);
  AddFunction(env, exports, "ChangeDirectory", ChangeDirectory);
  AddFunction(env, exports, "IsFileDropped", IsFileDropped);
  AddFunction(env, exports, "GetDroppedFiles", GetDroppedFiles);
  AddFunction(env, exports, "ClearDroppedFiles", ClearDroppedFiles);
  AddFunction(env, exports, "GetFileModTime", GetFileModTime);
  AddFunction(env, exports, "CompressData", CompressData);
  AddFunction(env, exports, "DecompressData", DecompressData);
  AddFunction(env, exports, "SaveStorageValue", SaveStorageValue);
  AddFunction(env, exports, "LoadStorageValue", LoadStorageValue);
  AddFunction(env, exports, "OpenURL", OpenURL);
  AddFunction(env, exports, "IsKeyPressed", IsKeyPressed);
  AddFunction(env, exports, "IsKeyDown", IsKeyDown);
  AddFunction(env, exports, "IsKeyReleased", IsKeyReleased);
  AddFunction(env, exports, "IsKeyUp", IsKeyUp);
  AddFunction(env, exports, "SetExitKey", SetExitKey);
  AddFunction(env, exports, "GetKeyPressed", GetKeyPressed);
  AddFunction(env, exports, "IsGamepadAvailable", IsGamepadAvailable);
  AddFunction(env, exports, "IsGamepadName", IsGamepadName);
  AddFunction(env, exports, "GetGamepadName", GetGamepadName);
  AddFunction(env, exports, "IsGamepadButtonPressed", IsGamepadButtonPressed);
  AddFunction(env, exports, "IsGamepadButtonDown", IsGamepadButtonDown);
  AddFunction(env, exports, "IsGamepadButtonReleased", IsGamepadButtonReleased);
  AddFunction(env, exports, "IsGamepadButtonUp", IsGamepadButtonUp);
  AddFunction(env, exports, "GetGamepadButtonPressed", GetGamepadButtonPressed);
  AddFunction(env, exports, "GetGamepadAxisCount", GetGamepadAxisCount);
  AddFunction(env, exports, "GetGamepadAxisMovement", GetGamepadAxisMovement);
  AddFunction(env, exports, "IsMouseButtonPressed", IsMouseButtonPressed);
  AddFunction(env, exports, "IsMouseButtonDown", IsMouseButtonDown);
  AddFunction(env, exports, "IsMouseButtonReleased", IsMouseButtonReleased);
  AddFunction(env, exports, "IsMouseButtonUp", IsMouseButtonUp);
  AddFunction(env, exports, "GetMouseX", GetMouseX);
  AddFunction(env, exports, "GetMouseY", GetMouseY);
  AddFunction(env, exports, "GetMousePosition", GetMousePosition);
  AddFunction(env, exports, "SetMousePosition", SetMousePosition);
  AddFunction(env, exports, "SetMouseOffset", SetMouseOffset);
  AddFunction(env, exports, "SetMouseScale", SetMouseScale);
  AddFunction(env, exports, "GetMouseWheelMove", GetMouseWheelMove);
  AddFunction(env, exports, "GetTouchX", GetTouchX);
  AddFunction(env, exports, "GetTouchY", GetTouchY);
  AddFunction(env, exports, "GetTouchPosition", GetTouchPosition);
  AddFunction(env, exports, "SetGesturesEnabled", SetGesturesEnabled);
  AddFunction(env, exports, "IsGestureDetected", IsGestureDetected);
  AddFunction(env, exports, "GetGestureDetected", GetGestureDetected);
  AddFunction(env, exports, "GetTouchPointsCount", GetTouchPointsCount);
  AddFunction(env, exports, "GetGestureHoldDuration", GetGestureHoldDuration);
  AddFunction(env, exports, "GetGestureDragVector", GetGestureDragVector);
  AddFunction(env, exports, "GetGestureDragAngle", GetGestureDragAngle);
  AddFunction(env, exports, "GetGesturePinchVector", GetGesturePinchVector);
  AddFunction(env, exports, "GetGesturePinchAngle", GetGesturePinchAngle);
  AddFunction(env, exports, "SetCameraMode", SetCameraMode);
  // AddFunction(env, exports, "UpdateCamera", UpdateCamera);
  AddFunction(env, exports, "SetCameraPanControl", SetCameraPanControl);
  AddFunction(env, exports, "SetCameraAltControl", SetCameraAltControl);
  AddFunction(env, exports, "SetCameraSmoothZoomControl", SetCameraSmoothZoomControl);
  AddFunction(env, exports, "SetCameraMoveControls", SetCameraMoveControls);
  AddFunction(env, exports, "DrawPixel", DrawPixel);
  AddFunction(env, exports, "DrawPixelV", DrawPixelV);
  AddFunction(env, exports, "DrawLine", DrawLine);
  AddFunction(env, exports, "DrawLineV", DrawLineV);
  AddFunction(env, exports, "DrawLineEx", DrawLineEx);
  AddFunction(env, exports, "DrawLineBezier", DrawLineBezier);
  AddFunction(env, exports, "DrawLineStrip", DrawLineStrip);
  AddFunction(env, exports, "DrawCircle", DrawCircle);
  AddFunction(env, exports, "DrawCircleSector", DrawCircleSector);
  AddFunction(env, exports, "DrawCircleSectorLines", DrawCircleSectorLines);
  AddFunction(env, exports, "DrawCircleGradient", DrawCircleGradient);
  AddFunction(env, exports, "DrawCircleV", DrawCircleV);
  AddFunction(env, exports, "DrawCircleLines", DrawCircleLines);
  AddFunction(env, exports, "DrawEllipse", DrawEllipse);
  AddFunction(env, exports, "DrawEllipseLines", DrawEllipseLines);
  AddFunction(env, exports, "DrawRing", DrawRing);
  AddFunction(env, exports, "DrawRingLines", DrawRingLines);
  AddFunction(env, exports, "DrawRectangle", DrawRectangle);
  AddFunction(env, exports, "DrawRectangleV", DrawRectangleV);
  AddFunction(env, exports, "DrawRectangleRec", DrawRectangleRec);
  AddFunction(env, exports, "DrawRectanglePro", DrawRectanglePro);
  AddFunction(env, exports, "DrawRectangleGradientV", DrawRectangleGradientV);
  AddFunction(env, exports, "DrawRectangleGradientH", DrawRectangleGradientH);
  AddFunction(env, exports, "DrawRectangleGradientEx", DrawRectangleGradientEx);
  AddFunction(env, exports, "DrawRectangleLines", DrawRectangleLines);
  AddFunction(env, exports, "DrawRectangleLinesEx", DrawRectangleLinesEx);
  AddFunction(env, exports, "DrawRectangleRounded", DrawRectangleRounded);
  AddFunction(env, exports, "DrawRectangleRoundedLines", DrawRectangleRoundedLines);
  AddFunction(env, exports, "DrawTriangle", DrawTriangle);
  AddFunction(env, exports, "DrawTriangleLines", DrawTriangleLines);
  AddFunction(env, exports, "DrawTriangleFan", DrawTriangleFan);
  AddFunction(env, exports, "DrawTriangleStrip", DrawTriangleStrip);
  AddFunction(env, exports, "DrawPoly", DrawPoly);
  AddFunction(env, exports, "DrawPolyLines", DrawPolyLines);
  AddFunction(env, exports, "CheckCollisionRecs", CheckCollisionRecs);
  AddFunction(env, exports, "CheckCollisionCircles", CheckCollisionCircles);
  AddFunction(env, exports, "CheckCollisionCircleRec", CheckCollisionCircleRec);
  AddFunction(env, exports, "GetCollisionRec", GetCollisionRec);
  AddFunction(env, exports, "CheckCollisionPointRec", CheckCollisionPointRec);
  AddFunction(env, exports, "CheckCollisionPointCircle", CheckCollisionPointCircle);
  AddFunction(env, exports, "CheckCollisionPointTriangle", CheckCollisionPointTriangle);
  AddFunction(env, exports, "LoadImage", LoadImage);
  AddFunction(env, exports, "LoadImageEx", LoadImageEx);
  AddFunction(env, exports, "LoadImageRaw", LoadImageRaw);
  AddFunction(env, exports, "UnloadImage", UnloadImage);
  AddFunction(env, exports, "ExportImage", ExportImage);
  AddFunction(env, exports, "ExportImageAsCode", ExportImageAsCode);
  AddFunction(env, exports, "GetImageData", GetImageData);
  AddFunction(env, exports, "GetImageDataNormalized", GetImageDataNormalized);
  AddFunction(env, exports, "GenImageColor", GenImageColor);
  AddFunction(env, exports, "GenImageGradientV", GenImageGradientV);
  AddFunction(env, exports, "GenImageGradientH", GenImageGradientH);
  AddFunction(env, exports, "GenImageGradientRadial", GenImageGradientRadial);
  AddFunction(env, exports, "GenImageChecked", GenImageChecked);
  AddFunction(env, exports, "GenImageWhiteNoise", GenImageWhiteNoise);
  AddFunction(env, exports, "GenImagePerlinNoise", GenImagePerlinNoise);
  AddFunction(env, exports, "GenImageCellular", GenImageCellular);
  AddFunction(env, exports, "ImageCopy", ImageCopy);
  AddFunction(env, exports, "ImageFromImage", ImageFromImage);
  AddFunction(env, exports, "ImageText", ImageText);
  AddFunction(env, exports, "ImageTextEx", ImageTextEx);
  AddFunction(env, exports, "ImageToPOT", ImageToPOT);
  AddFunction(env, exports, "ImageFormat", ImageFormat);
  AddFunction(env, exports, "ImageAlphaMask", ImageAlphaMask);
  AddFunction(env, exports, "ImageAlphaClear", ImageAlphaClear);
  AddFunction(env, exports, "ImageAlphaCrop", ImageAlphaCrop);
  AddFunction(env, exports, "ImageAlphaPremultiply", ImageAlphaPremultiply);
  AddFunction(env, exports, "ImageCrop", ImageCrop);
  AddFunction(env, exports, "ImageResize", ImageResize);
  AddFunction(env, exports, "ImageResizeNN", ImageResizeNN);
  AddFunction(env, exports, "ImageResizeCanvas", ImageResizeCanvas);
  AddFunction(env, exports, "ImageMipmaps", ImageMipmaps);
  AddFunction(env, exports, "ImageDither", ImageDither);
  AddFunction(env, exports, "ImageFlipVertical", ImageFlipVertical);
  AddFunction(env, exports, "ImageFlipHorizontal", ImageFlipHorizontal);
  AddFunction(env, exports, "ImageRotateCW", ImageRotateCW);
  AddFunction(env, exports, "ImageRotateCCW", ImageRotateCCW);
  AddFunction(env, exports, "ImageColorTint", ImageColorTint);
  AddFunction(env, exports, "ImageColorInvert", ImageColorInvert);
  AddFunction(env, exports, "ImageColorGrayscale", ImageColorGrayscale);
  AddFunction(env, exports, "ImageColorContrast", ImageColorContrast);
  AddFunction(env, exports, "ImageColorBrightness", ImageColorBrightness);
  AddFunction(env, exports, "ImageColorReplace", ImageColorReplace);
  AddFunction(env, exports, "ImageExtractPalette", ImageExtractPalette);
  AddFunction(env, exports, "GetImageAlphaBorder", GetImageAlphaBorder);
  AddFunction(env, exports, "ImageClearBackground", ImageClearBackground);
  AddFunction(env, exports, "ImageDrawPixel", ImageDrawPixel);
  AddFunction(env, exports, "ImageDrawPixelV", ImageDrawPixelV);
  AddFunction(env, exports, "ImageDrawLine", ImageDrawLine);
  AddFunction(env, exports, "ImageDrawLineV", ImageDrawLineV);
  AddFunction(env, exports, "ImageDrawCircle", ImageDrawCircle);
  AddFunction(env, exports, "ImageDrawCircleV", ImageDrawCircleV);
  AddFunction(env, exports, "ImageDrawRectangle", ImageDrawRectangle);
  AddFunction(env, exports, "ImageDrawRectangleV", ImageDrawRectangleV);
  AddFunction(env, exports, "ImageDrawRectangleRec", ImageDrawRectangleRec);
  AddFunction(env, exports, "ImageDrawRectangleLines", ImageDrawRectangleLines);
  AddFunction(env, exports, "ImageDraw", ImageDraw);
  AddFunction(env, exports, "ImageDrawText", ImageDrawText);
  AddFunction(env, exports, "ImageDrawTextEx", ImageDrawTextEx);
  AddFunction(env, exports, "LoadTexture", LoadTexture);
  AddFunction(env, exports, "LoadTextureFromImage", LoadTextureFromImage);
  AddFunction(env, exports, "LoadTextureCubemap", LoadTextureCubemap);
  AddFunction(env, exports, "LoadRenderTexture", LoadRenderTexture);
  AddFunction(env, exports, "UnloadTexture", UnloadTexture);
  AddFunction(env, exports, "UnloadRenderTexture", UnloadRenderTexture);
  AddFunction(env, exports, "UpdateTexture", UpdateTexture);
  AddFunction(env, exports, "GetTextureData", GetTextureData);
  AddFunction(env, exports, "GetScreenData", GetScreenData);
  AddFunction(env, exports, "GenTextureMipmaps", GenTextureMipmaps);
  AddFunction(env, exports, "SetTextureFilter", SetTextureFilter);
  AddFunction(env, exports, "SetTextureWrap", SetTextureWrap);
  AddFunction(env, exports, "DrawTexture", DrawTexture);
  AddFunction(env, exports, "DrawTextureV", DrawTextureV);
  AddFunction(env, exports, "DrawTextureEx", DrawTextureEx);
  AddFunction(env, exports, "DrawTextureRec", DrawTextureRec);
  AddFunction(env, exports, "DrawTextureQuad", DrawTextureQuad);
  AddFunction(env, exports, "DrawTexturePro", DrawTexturePro);
  AddFunction(env, exports, "DrawTextureNPatch", DrawTextureNPatch);
  AddFunction(env, exports, "GetPixelDataSize", GetPixelDataSize);
  AddFunction(env, exports, "GetFontDefault", GetFontDefault);
  AddFunction(env, exports, "LoadFont", LoadFont);
  AddFunction(env, exports, "LoadFontEx", LoadFontEx);
  AddFunction(env, exports, "LoadFontFromImage", LoadFontFromImage);
  AddFunction(env, exports, "LoadFontData", LoadFontData);
  AddFunction(env, exports, "GenImageFontAtlas", GenImageFontAtlas);
  AddFunction(env, exports, "UnloadFont", UnloadFont);
  AddFunction(env, exports, "DrawFPS", DrawFPS);
  AddFunction(env, exports, "DrawText", DrawText);
  AddFunction(env, exports, "DrawTextEx", DrawTextEx);
  AddFunction(env, exports, "DrawTextRec", DrawTextRec);
  // AddFunction(env, exports, "DrawTextRecEx", DrawTextRecEx);
  AddFunction(env, exports, "DrawTextCodepoint", DrawTextCodepoint);
  AddFunction(env, exports, "MeasureText", MeasureText);
  AddFunction(env, exports, "MeasureTextEx", MeasureTextEx);
  AddFunction(env, exports, "GetGlyphIndex", GetGlyphIndex);
  AddFunction(env, exports, "TextCopy", TextCopy);
  AddFunction(env, exports, "TextIsEqual", TextIsEqual);
  AddFunction(env, exports, "TextLength", TextLength);
  // AddFunction(env, exports, "TextFormat", TextFormat);
  AddFunction(env, exports, "TextSubtext", TextSubtext);
  AddFunction(env, exports, "TextReplace", TextReplace);
  AddFunction(env, exports, "TextInsert", TextInsert);
  AddFunction(env, exports, "TextJoin", TextJoin);
  AddFunction(env, exports, "TextSplit", TextSplit);
  AddFunction(env, exports, "TextAppend", TextAppend);
  AddFunction(env, exports, "TextFindIndex", TextFindIndex);
  AddFunction(env, exports, "TextToUpper", TextToUpper);
  AddFunction(env, exports, "TextToLower", TextToLower);
  AddFunction(env, exports, "TextToPascal", TextToPascal);
  AddFunction(env, exports, "TextToInteger", TextToInteger);
  AddFunction(env, exports, "TextToUtf8", TextToUtf8);
  AddFunction(env, exports, "GetCodepoints", GetCodepoints);
  AddFunction(env, exports, "GetCodepointsCount", GetCodepointsCount);
  AddFunction(env, exports, "GetNextCodepoint", GetNextCodepoint);
  AddFunction(env, exports, "CodepointToUtf8", CodepointToUtf8);
  AddFunction(env, exports, "DrawLine3D", DrawLine3D);
  AddFunction(env, exports, "DrawPoint3D", DrawPoint3D);
  AddFunction(env, exports, "DrawCircle3D", DrawCircle3D);
  AddFunction(env, exports, "DrawCube", DrawCube);
  AddFunction(env, exports, "DrawCubeV", DrawCubeV);
  AddFunction(env, exports, "DrawCubeWires", DrawCubeWires);
  AddFunction(env, exports, "DrawCubeWiresV", DrawCubeWiresV);
  AddFunction(env, exports, "DrawCubeTexture", DrawCubeTexture);
  AddFunction(env, exports, "DrawSphere", DrawSphere);
  AddFunction(env, exports, "DrawSphereEx", DrawSphereEx);
  AddFunction(env, exports, "DrawSphereWires", DrawSphereWires);
  AddFunction(env, exports, "DrawCylinder", DrawCylinder);
  AddFunction(env, exports, "DrawCylinderWires", DrawCylinderWires);
  AddFunction(env, exports, "DrawPlane", DrawPlane);
  AddFunction(env, exports, "DrawRay", DrawRay);
  AddFunction(env, exports, "DrawGrid", DrawGrid);
  AddFunction(env, exports, "DrawGizmo", DrawGizmo);
  // AddFunction(env, exports, "LoadModel", LoadModel);
  // AddFunction(env, exports, "LoadModelFromMesh", LoadModelFromMesh);
  // AddFunction(env, exports, "UnloadModel", UnloadModel);
  // AddFunction(env, exports, "LoadMeshes", LoadMeshes);
  // AddFunction(env, exports, "ExportMesh", ExportMesh);
  // AddFunction(env, exports, "UnloadMesh", UnloadMesh);
  // AddFunction(env, exports, "LoadMaterials", LoadMaterials);
  // AddFunction(env, exports, "LoadMaterialDefault", LoadMaterialDefault);
  // AddFunction(env, exports, "UnloadMaterial", UnloadMaterial);
  // AddFunction(env, exports, "SetMaterialTexture", SetMaterialTexture);
  // AddFunction(env, exports, "SetModelMeshMaterial", SetModelMeshMaterial);
  // AddFunction(env, exports, "LoadModelAnimations", LoadModelAnimations);
  // AddFunction(env, exports, "UpdateModelAnimation", UpdateModelAnimation);
  // AddFunction(env, exports, "UnloadModelAnimation", UnloadModelAnimation);
  // AddFunction(env, exports, "IsModelAnimationValid", IsModelAnimationValid);
  // AddFunction(env, exports, "GenMeshPoly", GenMeshPoly);
  // AddFunction(env, exports, "GenMeshPlane", GenMeshPlane);
  // AddFunction(env, exports, "GenMeshCube", GenMeshCube);
  // AddFunction(env, exports, "GenMeshSphere", GenMeshSphere);
  // AddFunction(env, exports, "GenMeshHemiSphere", GenMeshHemiSphere);
  // AddFunction(env, exports, "GenMeshCylinder", GenMeshCylinder);
  // AddFunction(env, exports, "GenMeshTorus", GenMeshTorus);
  // AddFunction(env, exports, "GenMeshKnot", GenMeshKnot);
  // AddFunction(env, exports, "GenMeshHeightmap", GenMeshHeightmap);
  // AddFunction(env, exports, "GenMeshCubicmap", GenMeshCubicmap);
  // AddFunction(env, exports, "MeshBoundingBox", MeshBoundingBox);
  // AddFunction(env, exports, "MeshTangents", MeshTangents);
  // AddFunction(env, exports, "MeshBinormals", MeshBinormals);
  // AddFunction(env, exports, "DrawModel", DrawModel);
  // AddFunction(env, exports, "DrawModelEx", DrawModelEx);
  // AddFunction(env, exports, "DrawModelWires", DrawModelWires);
  // AddFunction(env, exports, "DrawModelWiresEx", DrawModelWiresEx);
  AddFunction(env, exports, "DrawBoundingBox", DrawBoundingBox);
  AddFunction(env, exports, "DrawBillboard", DrawBillboard);
  AddFunction(env, exports, "DrawBillboardRec", DrawBillboardRec);
  AddFunction(env, exports, "CheckCollisionSpheres", CheckCollisionSpheres);
  AddFunction(env, exports, "CheckCollisionBoxes", CheckCollisionBoxes);
  AddFunction(env, exports, "CheckCollisionBoxSphere", CheckCollisionBoxSphere);
  AddFunction(env, exports, "CheckCollisionRaySphere", CheckCollisionRaySphere);
  AddFunction(env, exports, "CheckCollisionRaySphereEx", CheckCollisionRaySphereEx);
  AddFunction(env, exports, "CheckCollisionRayBox", CheckCollisionRayBox);
  AddFunction(env, exports, "GetCollisionRayModel", GetCollisionRayModel);
  AddFunction(env, exports, "GetCollisionRayTriangle", GetCollisionRayTriangle);
  AddFunction(env, exports, "GetCollisionRayGround", GetCollisionRayGround);
  AddFunction(env, exports, "LoadShader", LoadShader);
  AddFunction(env, exports, "LoadShaderCode", LoadShaderCode);
  AddFunction(env, exports, "UnloadShader", UnloadShader);
  AddFunction(env, exports, "GetShaderDefault", GetShaderDefault);
  AddFunction(env, exports, "GetTextureDefault", GetTextureDefault);
  AddFunction(env, exports, "GetShapesTexture", GetShapesTexture);
  AddFunction(env, exports, "GetShapesTextureRec", GetShapesTextureRec);
  AddFunction(env, exports, "SetShapesTexture", SetShapesTexture);
  AddFunction(env, exports, "GetShaderLocation", GetShaderLocation);
  AddFunction(env, exports, "SetShaderValue", SetShaderValue);
  AddFunction(env, exports, "SetShaderValueV", SetShaderValueV);
  AddFunction(env, exports, "SetShaderValueMatrix", SetShaderValueMatrix);
  AddFunction(env, exports, "SetShaderValueTexture", SetShaderValueTexture);
  AddFunction(env, exports, "SetMatrixProjection", SetMatrixProjection);
  // AddFunction(env, exports, "SetMatrixModelview", SetMatrixModelview);
  // AddFunction(env, exports, "GetMatrixModelview", GetMatrixModelview);
  AddFunction(env, exports, "GetMatrixProjection", GetMatrixProjection);
  AddFunction(env, exports, "GenTextureCubemap", GenTextureCubemap);
  AddFunction(env, exports, "GenTextureIrradiance", GenTextureIrradiance);
  AddFunction(env, exports, "GenTexturePrefilter", GenTexturePrefilter);
  AddFunction(env, exports, "GenTextureBRDF", GenTextureBRDF);
  AddFunction(env, exports, "BeginShaderMode", BeginShaderMode);
  AddFunction(env, exports, "EndShaderMode", EndShaderMode);
  AddFunction(env, exports, "BeginBlendMode", BeginBlendMode);
  AddFunction(env, exports, "EndBlendMode", EndBlendMode);
  AddFunction(env, exports, "InitVrSimulator", InitVrSimulator);
  AddFunction(env, exports, "CloseVrSimulator", CloseVrSimulator);
  // AddFunction(env, exports, "UpdateVrTracking", UpdateVrTracking);
  AddFunction(env, exports, "SetVrConfiguration", SetVrConfiguration);
  AddFunction(env, exports, "IsVrSimulatorReady", IsVrSimulatorReady);
  AddFunction(env, exports, "ToggleVrMode", ToggleVrMode);
  AddFunction(env, exports, "BeginVrDrawing", BeginVrDrawing);
  AddFunction(env, exports, "EndVrDrawing", EndVrDrawing);
  AddFunction(env, exports, "InitAudioDevice", InitAudioDevice);
  AddFunction(env, exports, "CloseAudioDevice", CloseAudioDevice);
  AddFunction(env, exports, "IsAudioDeviceReady", IsAudioDeviceReady);
  AddFunction(env, exports, "SetMasterVolume", SetMasterVolume);
  AddFunction(env, exports, "LoadWave", LoadWave);
  AddFunction(env, exports, "LoadSound", LoadSound);
  AddFunction(env, exports, "LoadSoundFromWave", LoadSoundFromWave);
  AddFunction(env, exports, "UpdateSound", UpdateSound);
  AddFunction(env, exports, "UnloadWave", UnloadWave);
  AddFunction(env, exports, "UnloadSound", UnloadSound);
  AddFunction(env, exports, "ExportWave", ExportWave);
  AddFunction(env, exports, "ExportWaveAsCode", ExportWaveAsCode);
  AddFunction(env, exports, "PlaySound", PlaySound);
  AddFunction(env, exports, "StopSound", StopSound);
  AddFunction(env, exports, "PauseSound", PauseSound);
  AddFunction(env, exports, "ResumeSound", ResumeSound);
  AddFunction(env, exports, "PlaySoundMulti", PlaySoundMulti);
  AddFunction(env, exports, "StopSoundMulti", StopSoundMulti);
  AddFunction(env, exports, "GetSoundsPlaying", GetSoundsPlaying);
  AddFunction(env, exports, "IsSoundPlaying", IsSoundPlaying);
  AddFunction(env, exports, "SetSoundVolume", SetSoundVolume);
  AddFunction(env, exports, "SetSoundPitch", SetSoundPitch);
  AddFunction(env, exports, "WaveFormat", WaveFormat);
  AddFunction(env, exports, "WaveCopy", WaveCopy);
  AddFunction(env, exports, "WaveCrop", WaveCrop);
  AddFunction(env, exports, "GetWaveData", GetWaveData);
  AddFunction(env, exports, "LoadMusicStream", LoadMusicStream);
  AddFunction(env, exports, "UnloadMusicStream", UnloadMusicStream);
  AddFunction(env, exports, "PlayMusicStream", PlayMusicStream);
  AddFunction(env, exports, "UpdateMusicStream", UpdateMusicStream);
  AddFunction(env, exports, "StopMusicStream", StopMusicStream);
  AddFunction(env, exports, "PauseMusicStream", PauseMusicStream);
  AddFunction(env, exports, "ResumeMusicStream", ResumeMusicStream);
  AddFunction(env, exports, "IsMusicPlaying", IsMusicPlaying);
  AddFunction(env, exports, "SetMusicVolume", SetMusicVolume);
  AddFunction(env, exports, "SetMusicPitch", SetMusicPitch);
  AddFunction(env, exports, "SetMusicLoopCount", SetMusicLoopCount);
  AddFunction(env, exports, "GetMusicTimeLength", GetMusicTimeLength);
  AddFunction(env, exports, "GetMusicTimePlayed", GetMusicTimePlayed);
  AddFunction(env, exports, "InitAudioStream", InitAudioStream);
  AddFunction(env, exports, "UpdateAudioStream", UpdateAudioStream);
  AddFunction(env, exports, "CloseAudioStream", CloseAudioStream);
  AddFunction(env, exports, "IsAudioStreamProcessed", IsAudioStreamProcessed);
  AddFunction(env, exports, "PlayAudioStream", PlayAudioStream);
  AddFunction(env, exports, "PauseAudioStream", PauseAudioStream);
  AddFunction(env, exports, "ResumeAudioStream", ResumeAudioStream);
  AddFunction(env, exports, "IsAudioStreamPlaying", IsAudioStreamPlaying);
  AddFunction(env, exports, "StopAudioStream", StopAudioStream);
  AddFunction(env, exports, "SetAudioStreamVolume", SetAudioStreamVolume);
  AddFunction(env, exports, "SetAudioStreamPitch", SetAudioStreamPitch);
  AddFunction(env, exports, "SetAudioStreamBufferSizeDefault", SetAudioStreamBufferSizeDefault);
}

#endif
